package com.dsw.iot.model;

import java.util.Date;

public class CardLocateDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_locate.id
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_locate.card_id
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    private String cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_locate.register_id
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    private Long registerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_locate.tag_id
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    private Integer tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_locate.tag_euid
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    private String tagEuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_locate.localX
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    private Long localX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_locate.localY
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    private Long localY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_locate.localZ
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    private Long localZ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_locate.addTime
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_locate.tagAlias
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    private String tagalias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_locate.tagGender
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    private String taggender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_locate.is_history
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    private String isHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_locate.is_deleted
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_locate.create_time
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_locate.create_user
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_locate.update_time
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_locate.update_user
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_locate.remark
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_locate.id
     *
     * @return the value of card_locate.id
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_locate.id
     *
     * @param id the value for card_locate.id
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_locate.card_id
     *
     * @return the value of card_locate.card_id
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_locate.card_id
     *
     * @param cardId the value for card_locate.card_id
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public void setCardId(String cardId) {
        this.cardId = cardId == null ? null : cardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_locate.register_id
     *
     * @return the value of card_locate.register_id
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public Long getRegisterId() {
        return registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_locate.register_id
     *
     * @param registerId the value for card_locate.register_id
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public void setRegisterId(Long registerId) {
        this.registerId = registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_locate.tag_id
     *
     * @return the value of card_locate.tag_id
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_locate.tag_id
     *
     * @param tagId the value for card_locate.tag_id
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_locate.tag_euid
     *
     * @return the value of card_locate.tag_euid
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public String getTagEuid() {
        return tagEuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_locate.tag_euid
     *
     * @param tagEuid the value for card_locate.tag_euid
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public void setTagEuid(String tagEuid) {
        this.tagEuid = tagEuid == null ? null : tagEuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_locate.localX
     *
     * @return the value of card_locate.localX
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public Long getLocalX() {
        return localX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_locate.localX
     *
     * @param localX the value for card_locate.localX
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public void setLocalX(Long localX) {
        this.localX = localX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_locate.localY
     *
     * @return the value of card_locate.localY
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public Long getLocalY() {
        return localY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_locate.localY
     *
     * @param localY the value for card_locate.localY
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public void setLocalY(Long localY) {
        this.localY = localY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_locate.localZ
     *
     * @return the value of card_locate.localZ
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public Long getLocalZ() {
        return localZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_locate.localZ
     *
     * @param localZ the value for card_locate.localZ
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public void setLocalZ(Long localZ) {
        this.localZ = localZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_locate.addTime
     *
     * @return the value of card_locate.addTime
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_locate.addTime
     *
     * @param addTime the value for card_locate.addTime
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_locate.tagAlias
     *
     * @return the value of card_locate.tagAlias
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public String getTagalias() {
        return tagalias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_locate.tagAlias
     *
     * @param tagalias the value for card_locate.tagAlias
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public void setTagalias(String tagalias) {
        this.tagalias = tagalias == null ? null : tagalias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_locate.tagGender
     *
     * @return the value of card_locate.tagGender
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public String getTaggender() {
        return taggender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_locate.tagGender
     *
     * @param taggender the value for card_locate.tagGender
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public void setTaggender(String taggender) {
        this.taggender = taggender == null ? null : taggender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_locate.is_history
     *
     * @return the value of card_locate.is_history
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public String getIsHistory() {
        return isHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_locate.is_history
     *
     * @param isHistory the value for card_locate.is_history
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public void setIsHistory(String isHistory) {
        this.isHistory = isHistory == null ? null : isHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_locate.is_deleted
     *
     * @return the value of card_locate.is_deleted
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_locate.is_deleted
     *
     * @param isDeleted the value for card_locate.is_deleted
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_locate.create_time
     *
     * @return the value of card_locate.create_time
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_locate.create_time
     *
     * @param createTime the value for card_locate.create_time
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_locate.create_user
     *
     * @return the value of card_locate.create_user
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_locate.create_user
     *
     * @param createUser the value for card_locate.create_user
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_locate.update_time
     *
     * @return the value of card_locate.update_time
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_locate.update_time
     *
     * @param updateTime the value for card_locate.update_time
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_locate.update_user
     *
     * @return the value of card_locate.update_user
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_locate.update_user
     *
     * @param updateUser the value for card_locate.update_user
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_locate.remark
     *
     * @return the value of card_locate.remark
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_locate.remark
     *
     * @param remark the value for card_locate.remark
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}