package com.dsw.iot.model;

import java.util.Date;

public class DictionaryDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.id
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.pid
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    private Long pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.code
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.type
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.name
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.is_system
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    private String isSystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.sort
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.remark
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.is_deleted
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.create_time
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.create_user
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.update_time
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.update_user
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.id
     *
     * @return the value of dictionary.id
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.id
     *
     * @param id the value for dictionary.id
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.pid
     *
     * @return the value of dictionary.pid
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.pid
     *
     * @param pid the value for dictionary.pid
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.code
     *
     * @return the value of dictionary.code
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.code
     *
     * @param code the value for dictionary.code
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.type
     *
     * @return the value of dictionary.type
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.type
     *
     * @param type the value for dictionary.type
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.name
     *
     * @return the value of dictionary.name
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.name
     *
     * @param name the value for dictionary.name
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.is_system
     *
     * @return the value of dictionary.is_system
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    public String getIsSystem() {
        return isSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.is_system
     *
     * @param isSystem the value for dictionary.is_system
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    public void setIsSystem(String isSystem) {
        this.isSystem = isSystem == null ? null : isSystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.sort
     *
     * @return the value of dictionary.sort
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.sort
     *
     * @param sort the value for dictionary.sort
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.remark
     *
     * @return the value of dictionary.remark
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.remark
     *
     * @param remark the value for dictionary.remark
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.is_deleted
     *
     * @return the value of dictionary.is_deleted
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.is_deleted
     *
     * @param isDeleted the value for dictionary.is_deleted
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.create_time
     *
     * @return the value of dictionary.create_time
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.create_time
     *
     * @param createTime the value for dictionary.create_time
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.create_user
     *
     * @return the value of dictionary.create_user
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.create_user
     *
     * @param createUser the value for dictionary.create_user
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.update_time
     *
     * @return the value of dictionary.update_time
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.update_time
     *
     * @param updateTime the value for dictionary.update_time
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.update_user
     *
     * @return the value of dictionary.update_user
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.update_user
     *
     * @param updateUser the value for dictionary.update_user
     *
     * @mbggenerated Mon Feb 05 17:02:02 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}