package com.dsw.iot.model;

import java.util.Date;

public class FaceBaseDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_base.id
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_base.catch_id
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    private Long catchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_base.face_id
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    private String faceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_base.group_id
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_base.score
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    private Double score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_base.threshold
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    private Double threshold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_base.card_id
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    private String cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_base.name
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_base.role_id
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_base.alert_type
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    private Integer alertType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_base.is_deleted
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_base.create_time
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_base.create_user
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_base.update_time
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_base.update_user
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_base.remark
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_base.id
     *
     * @return the value of face_base.id
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_base.id
     *
     * @param id the value for face_base.id
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_base.catch_id
     *
     * @return the value of face_base.catch_id
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public Long getCatchId() {
        return catchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_base.catch_id
     *
     * @param catchId the value for face_base.catch_id
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public void setCatchId(Long catchId) {
        this.catchId = catchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_base.face_id
     *
     * @return the value of face_base.face_id
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public String getFaceId() {
        return faceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_base.face_id
     *
     * @param faceId the value for face_base.face_id
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public void setFaceId(String faceId) {
        this.faceId = faceId == null ? null : faceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_base.group_id
     *
     * @return the value of face_base.group_id
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_base.group_id
     *
     * @param groupId the value for face_base.group_id
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_base.score
     *
     * @return the value of face_base.score
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_base.score
     *
     * @param score the value for face_base.score
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_base.threshold
     *
     * @return the value of face_base.threshold
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public Double getThreshold() {
        return threshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_base.threshold
     *
     * @param threshold the value for face_base.threshold
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public void setThreshold(Double threshold) {
        this.threshold = threshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_base.card_id
     *
     * @return the value of face_base.card_id
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_base.card_id
     *
     * @param cardId the value for face_base.card_id
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public void setCardId(String cardId) {
        this.cardId = cardId == null ? null : cardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_base.name
     *
     * @return the value of face_base.name
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_base.name
     *
     * @param name the value for face_base.name
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_base.role_id
     *
     * @return the value of face_base.role_id
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_base.role_id
     *
     * @param roleId the value for face_base.role_id
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_base.alert_type
     *
     * @return the value of face_base.alert_type
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public Integer getAlertType() {
        return alertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_base.alert_type
     *
     * @param alertType the value for face_base.alert_type
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public void setAlertType(Integer alertType) {
        this.alertType = alertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_base.is_deleted
     *
     * @return the value of face_base.is_deleted
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_base.is_deleted
     *
     * @param isDeleted the value for face_base.is_deleted
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_base.create_time
     *
     * @return the value of face_base.create_time
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_base.create_time
     *
     * @param createTime the value for face_base.create_time
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_base.create_user
     *
     * @return the value of face_base.create_user
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_base.create_user
     *
     * @param createUser the value for face_base.create_user
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_base.update_time
     *
     * @return the value of face_base.update_time
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_base.update_time
     *
     * @param updateTime the value for face_base.update_time
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_base.update_user
     *
     * @return the value of face_base.update_user
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_base.update_user
     *
     * @param updateUser the value for face_base.update_user
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_base.remark
     *
     * @return the value of face_base.remark
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_base.remark
     *
     * @param remark the value for face_base.remark
     *
     * @mbggenerated Thu Mar 15 17:22:06 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}