package com.dsw.iot.model;

import java.util.Date;

public class InjuryRegisterDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column injury_register.id
     *
     * @mbggenerated Fri Mar 02 12:23:00 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column injury_register.register_id
     *
     * @mbggenerated Fri Mar 02 12:23:00 CST 2018
     */
    private Long registerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column injury_register.part
     *
     * @mbggenerated Fri Mar 02 12:23:00 CST 2018
     */
    private String part;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column injury_register.remark
     *
     * @mbggenerated Fri Mar 02 12:23:00 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column injury_register.is_deleted
     *
     * @mbggenerated Fri Mar 02 12:23:00 CST 2018
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column injury_register.create_time
     *
     * @mbggenerated Fri Mar 02 12:23:00 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column injury_register.create_user
     *
     * @mbggenerated Fri Mar 02 12:23:00 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column injury_register.update_time
     *
     * @mbggenerated Fri Mar 02 12:23:00 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column injury_register.update_user
     *
     * @mbggenerated Fri Mar 02 12:23:00 CST 2018
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column injury_register.id
     *
     * @return the value of injury_register.id
     *
     * @mbggenerated Fri Mar 02 12:23:00 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column injury_register.id
     *
     * @param id the value for injury_register.id
     *
     * @mbggenerated Fri Mar 02 12:23:00 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column injury_register.register_id
     *
     * @return the value of injury_register.register_id
     *
     * @mbggenerated Fri Mar 02 12:23:00 CST 2018
     */
    public Long getRegisterId() {
        return registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column injury_register.register_id
     *
     * @param registerId the value for injury_register.register_id
     *
     * @mbggenerated Fri Mar 02 12:23:00 CST 2018
     */
    public void setRegisterId(Long registerId) {
        this.registerId = registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column injury_register.part
     *
     * @return the value of injury_register.part
     *
     * @mbggenerated Fri Mar 02 12:23:00 CST 2018
     */
    public String getPart() {
        return part;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column injury_register.part
     *
     * @param part the value for injury_register.part
     *
     * @mbggenerated Fri Mar 02 12:23:00 CST 2018
     */
    public void setPart(String part) {
        this.part = part == null ? null : part.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column injury_register.remark
     *
     * @return the value of injury_register.remark
     *
     * @mbggenerated Fri Mar 02 12:23:00 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column injury_register.remark
     *
     * @param remark the value for injury_register.remark
     *
     * @mbggenerated Fri Mar 02 12:23:00 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column injury_register.is_deleted
     *
     * @return the value of injury_register.is_deleted
     *
     * @mbggenerated Fri Mar 02 12:23:00 CST 2018
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column injury_register.is_deleted
     *
     * @param isDeleted the value for injury_register.is_deleted
     *
     * @mbggenerated Fri Mar 02 12:23:00 CST 2018
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column injury_register.create_time
     *
     * @return the value of injury_register.create_time
     *
     * @mbggenerated Fri Mar 02 12:23:00 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column injury_register.create_time
     *
     * @param createTime the value for injury_register.create_time
     *
     * @mbggenerated Fri Mar 02 12:23:00 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column injury_register.create_user
     *
     * @return the value of injury_register.create_user
     *
     * @mbggenerated Fri Mar 02 12:23:00 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column injury_register.create_user
     *
     * @param createUser the value for injury_register.create_user
     *
     * @mbggenerated Fri Mar 02 12:23:00 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column injury_register.update_time
     *
     * @return the value of injury_register.update_time
     *
     * @mbggenerated Fri Mar 02 12:23:00 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column injury_register.update_time
     *
     * @param updateTime the value for injury_register.update_time
     *
     * @mbggenerated Fri Mar 02 12:23:00 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column injury_register.update_user
     *
     * @return the value of injury_register.update_user
     *
     * @mbggenerated Fri Mar 02 12:23:00 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column injury_register.update_user
     *
     * @param updateUser the value for injury_register.update_user
     *
     * @mbggenerated Fri Mar 02 12:23:00 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}