package com.dsw.iot.model;

import java.util.Date;

public class OutConfirmDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_confirm.id
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_confirm.register_id
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private Long registerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_confirm.apply_type
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private String applyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_confirm.apply_reason
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private String applyReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_confirm.is_return
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private String isReturn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_confirm.audit_content
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private String auditContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_confirm.audit_user
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private String auditUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_confirm.audit_date
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private Date auditDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_confirm.status
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_confirm.apply_date
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private Date applyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_confirm.is_escort
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private String isEscort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_confirm.escort_police
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private String escortPolice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_confirm.remind_id
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private String remindId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_confirm.out_type
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private String outType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_confirm.is_history
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private String isHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_confirm.out_date
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private Date outDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_confirm.back_date
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private Date backDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_confirm.is_deleted
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_confirm.create_time
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_confirm.create_user
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_confirm.update_time
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_confirm.update_user
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_confirm.remark
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_confirm.id
     *
     * @return the value of out_confirm.id
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_confirm.id
     *
     * @param id the value for out_confirm.id
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_confirm.register_id
     *
     * @return the value of out_confirm.register_id
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public Long getRegisterId() {
        return registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_confirm.register_id
     *
     * @param registerId the value for out_confirm.register_id
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setRegisterId(Long registerId) {
        this.registerId = registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_confirm.apply_type
     *
     * @return the value of out_confirm.apply_type
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public String getApplyType() {
        return applyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_confirm.apply_type
     *
     * @param applyType the value for out_confirm.apply_type
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setApplyType(String applyType) {
        this.applyType = applyType == null ? null : applyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_confirm.apply_reason
     *
     * @return the value of out_confirm.apply_reason
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public String getApplyReason() {
        return applyReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_confirm.apply_reason
     *
     * @param applyReason the value for out_confirm.apply_reason
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setApplyReason(String applyReason) {
        this.applyReason = applyReason == null ? null : applyReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_confirm.is_return
     *
     * @return the value of out_confirm.is_return
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public String getIsReturn() {
        return isReturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_confirm.is_return
     *
     * @param isReturn the value for out_confirm.is_return
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setIsReturn(String isReturn) {
        this.isReturn = isReturn == null ? null : isReturn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_confirm.audit_content
     *
     * @return the value of out_confirm.audit_content
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public String getAuditContent() {
        return auditContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_confirm.audit_content
     *
     * @param auditContent the value for out_confirm.audit_content
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setAuditContent(String auditContent) {
        this.auditContent = auditContent == null ? null : auditContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_confirm.audit_user
     *
     * @return the value of out_confirm.audit_user
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public String getAuditUser() {
        return auditUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_confirm.audit_user
     *
     * @param auditUser the value for out_confirm.audit_user
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setAuditUser(String auditUser) {
        this.auditUser = auditUser == null ? null : auditUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_confirm.audit_date
     *
     * @return the value of out_confirm.audit_date
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public Date getAuditDate() {
        return auditDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_confirm.audit_date
     *
     * @param auditDate the value for out_confirm.audit_date
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setAuditDate(Date auditDate) {
        this.auditDate = auditDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_confirm.status
     *
     * @return the value of out_confirm.status
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_confirm.status
     *
     * @param status the value for out_confirm.status
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_confirm.apply_date
     *
     * @return the value of out_confirm.apply_date
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public Date getApplyDate() {
        return applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_confirm.apply_date
     *
     * @param applyDate the value for out_confirm.apply_date
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setApplyDate(Date applyDate) {
        this.applyDate = applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_confirm.is_escort
     *
     * @return the value of out_confirm.is_escort
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public String getIsEscort() {
        return isEscort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_confirm.is_escort
     *
     * @param isEscort the value for out_confirm.is_escort
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setIsEscort(String isEscort) {
        this.isEscort = isEscort == null ? null : isEscort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_confirm.escort_police
     *
     * @return the value of out_confirm.escort_police
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public String getEscortPolice() {
        return escortPolice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_confirm.escort_police
     *
     * @param escortPolice the value for out_confirm.escort_police
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setEscortPolice(String escortPolice) {
        this.escortPolice = escortPolice == null ? null : escortPolice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_confirm.remind_id
     *
     * @return the value of out_confirm.remind_id
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public String getRemindId() {
        return remindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_confirm.remind_id
     *
     * @param remindId the value for out_confirm.remind_id
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setRemindId(String remindId) {
        this.remindId = remindId == null ? null : remindId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_confirm.out_type
     *
     * @return the value of out_confirm.out_type
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public String getOutType() {
        return outType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_confirm.out_type
     *
     * @param outType the value for out_confirm.out_type
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setOutType(String outType) {
        this.outType = outType == null ? null : outType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_confirm.is_history
     *
     * @return the value of out_confirm.is_history
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public String getIsHistory() {
        return isHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_confirm.is_history
     *
     * @param isHistory the value for out_confirm.is_history
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setIsHistory(String isHistory) {
        this.isHistory = isHistory == null ? null : isHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_confirm.out_date
     *
     * @return the value of out_confirm.out_date
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public Date getOutDate() {
        return outDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_confirm.out_date
     *
     * @param outDate the value for out_confirm.out_date
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setOutDate(Date outDate) {
        this.outDate = outDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_confirm.back_date
     *
     * @return the value of out_confirm.back_date
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public Date getBackDate() {
        return backDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_confirm.back_date
     *
     * @param backDate the value for out_confirm.back_date
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setBackDate(Date backDate) {
        this.backDate = backDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_confirm.is_deleted
     *
     * @return the value of out_confirm.is_deleted
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_confirm.is_deleted
     *
     * @param isDeleted the value for out_confirm.is_deleted
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_confirm.create_time
     *
     * @return the value of out_confirm.create_time
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_confirm.create_time
     *
     * @param createTime the value for out_confirm.create_time
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_confirm.create_user
     *
     * @return the value of out_confirm.create_user
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_confirm.create_user
     *
     * @param createUser the value for out_confirm.create_user
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_confirm.update_time
     *
     * @return the value of out_confirm.update_time
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_confirm.update_time
     *
     * @param updateTime the value for out_confirm.update_time
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_confirm.update_user
     *
     * @return the value of out_confirm.update_user
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_confirm.update_user
     *
     * @param updateUser the value for out_confirm.update_user
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_confirm.remark
     *
     * @return the value of out_confirm.remark
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_confirm.remark
     *
     * @param remark the value for out_confirm.remark
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}