package com.dsw.iot.model;

import java.util.Date;

public class RelatedPhoneConfirmDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column related_phone_confirm.id
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column related_phone_confirm.register_id
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private Long registerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column related_phone_confirm.police_name
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private String policeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column related_phone_confirm.call_name
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private String callName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column related_phone_confirm.apply_reason
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private String applyReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column related_phone_confirm.talk_time
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private String talkTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column related_phone_confirm.apply_time
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private Date applyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column related_phone_confirm.tel
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column related_phone_confirm.check_man
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private String checkMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column related_phone_confirm.check_status
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private String checkStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column related_phone_confirm.check_time
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private Date checkTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column related_phone_confirm.check_content
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private String checkContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column related_phone_confirm.audio_path
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private String audioPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column related_phone_confirm.is_deleted
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column related_phone_confirm.create_time
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column related_phone_confirm.create_user
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column related_phone_confirm.update_time
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column related_phone_confirm.update_user
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column related_phone_confirm.remark
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column related_phone_confirm.id
     *
     * @return the value of related_phone_confirm.id
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column related_phone_confirm.id
     *
     * @param id the value for related_phone_confirm.id
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column related_phone_confirm.register_id
     *
     * @return the value of related_phone_confirm.register_id
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public Long getRegisterId() {
        return registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column related_phone_confirm.register_id
     *
     * @param registerId the value for related_phone_confirm.register_id
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setRegisterId(Long registerId) {
        this.registerId = registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column related_phone_confirm.police_name
     *
     * @return the value of related_phone_confirm.police_name
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public String getPoliceName() {
        return policeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column related_phone_confirm.police_name
     *
     * @param policeName the value for related_phone_confirm.police_name
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setPoliceName(String policeName) {
        this.policeName = policeName == null ? null : policeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column related_phone_confirm.call_name
     *
     * @return the value of related_phone_confirm.call_name
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public String getCallName() {
        return callName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column related_phone_confirm.call_name
     *
     * @param callName the value for related_phone_confirm.call_name
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setCallName(String callName) {
        this.callName = callName == null ? null : callName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column related_phone_confirm.apply_reason
     *
     * @return the value of related_phone_confirm.apply_reason
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public String getApplyReason() {
        return applyReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column related_phone_confirm.apply_reason
     *
     * @param applyReason the value for related_phone_confirm.apply_reason
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setApplyReason(String applyReason) {
        this.applyReason = applyReason == null ? null : applyReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column related_phone_confirm.talk_time
     *
     * @return the value of related_phone_confirm.talk_time
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public String getTalkTime() {
        return talkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column related_phone_confirm.talk_time
     *
     * @param talkTime the value for related_phone_confirm.talk_time
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setTalkTime(String talkTime) {
        this.talkTime = talkTime == null ? null : talkTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column related_phone_confirm.apply_time
     *
     * @return the value of related_phone_confirm.apply_time
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column related_phone_confirm.apply_time
     *
     * @param applyTime the value for related_phone_confirm.apply_time
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column related_phone_confirm.tel
     *
     * @return the value of related_phone_confirm.tel
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column related_phone_confirm.tel
     *
     * @param tel the value for related_phone_confirm.tel
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column related_phone_confirm.check_man
     *
     * @return the value of related_phone_confirm.check_man
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public String getCheckMan() {
        return checkMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column related_phone_confirm.check_man
     *
     * @param checkMan the value for related_phone_confirm.check_man
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setCheckMan(String checkMan) {
        this.checkMan = checkMan == null ? null : checkMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column related_phone_confirm.check_status
     *
     * @return the value of related_phone_confirm.check_status
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public String getCheckStatus() {
        return checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column related_phone_confirm.check_status
     *
     * @param checkStatus the value for related_phone_confirm.check_status
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setCheckStatus(String checkStatus) {
        this.checkStatus = checkStatus == null ? null : checkStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column related_phone_confirm.check_time
     *
     * @return the value of related_phone_confirm.check_time
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column related_phone_confirm.check_time
     *
     * @param checkTime the value for related_phone_confirm.check_time
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column related_phone_confirm.check_content
     *
     * @return the value of related_phone_confirm.check_content
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public String getCheckContent() {
        return checkContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column related_phone_confirm.check_content
     *
     * @param checkContent the value for related_phone_confirm.check_content
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setCheckContent(String checkContent) {
        this.checkContent = checkContent == null ? null : checkContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column related_phone_confirm.audio_path
     *
     * @return the value of related_phone_confirm.audio_path
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public String getAudioPath() {
        return audioPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column related_phone_confirm.audio_path
     *
     * @param audioPath the value for related_phone_confirm.audio_path
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setAudioPath(String audioPath) {
        this.audioPath = audioPath == null ? null : audioPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column related_phone_confirm.is_deleted
     *
     * @return the value of related_phone_confirm.is_deleted
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column related_phone_confirm.is_deleted
     *
     * @param isDeleted the value for related_phone_confirm.is_deleted
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column related_phone_confirm.create_time
     *
     * @return the value of related_phone_confirm.create_time
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column related_phone_confirm.create_time
     *
     * @param createTime the value for related_phone_confirm.create_time
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column related_phone_confirm.create_user
     *
     * @return the value of related_phone_confirm.create_user
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column related_phone_confirm.create_user
     *
     * @param createUser the value for related_phone_confirm.create_user
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column related_phone_confirm.update_time
     *
     * @return the value of related_phone_confirm.update_time
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column related_phone_confirm.update_time
     *
     * @param updateTime the value for related_phone_confirm.update_time
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column related_phone_confirm.update_user
     *
     * @return the value of related_phone_confirm.update_user
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column related_phone_confirm.update_user
     *
     * @param updateUser the value for related_phone_confirm.update_user
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column related_phone_confirm.remark
     *
     * @return the value of related_phone_confirm.remark
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column related_phone_confirm.remark
     *
     * @param remark the value for related_phone_confirm.remark
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}