package com.dsw.iot.model;

import com.dsw.iot.util.PageDto;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RoomAreaDoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room_area
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room_area
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room_area
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room_area
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    protected PageDto pageDto;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_area
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public RoomAreaDoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_area
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_area
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_area
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_area
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_area
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_area
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_area
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_area
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_area
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_area
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_area
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public void setPageDto(PageDto pageDto) {
        this.pageDto=pageDto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_area
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public PageDto getPageDto() {
        return pageDto;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room_area
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRoomNameIsNull() {
            addCriterion("room_name is null");
            return (Criteria) this;
        }

        public Criteria andRoomNameIsNotNull() {
            addCriterion("room_name is not null");
            return (Criteria) this;
        }

        public Criteria andRoomNameEqualTo(String value) {
            addCriterion("room_name =", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameNotEqualTo(String value) {
            addCriterion("room_name <>", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameGreaterThan(String value) {
            addCriterion("room_name >", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameGreaterThanOrEqualTo(String value) {
            addCriterion("room_name >=", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameLessThan(String value) {
            addCriterion("room_name <", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameLessThanOrEqualTo(String value) {
            addCriterion("room_name <=", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameLike(String value) {
            addCriterion("room_name like", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameNotLike(String value) {
            addCriterion("room_name not like", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameIn(List<String> values) {
            addCriterion("room_name in", values, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameNotIn(List<String> values) {
            addCriterion("room_name not in", values, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameBetween(String value1, String value2) {
            addCriterion("room_name between", value1, value2, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameNotBetween(String value1, String value2) {
            addCriterion("room_name not between", value1, value2, "roomName");
            return (Criteria) this;
        }

        public Criteria andBeginXIsNull() {
            addCriterion("beginX is null");
            return (Criteria) this;
        }

        public Criteria andBeginXIsNotNull() {
            addCriterion("beginX is not null");
            return (Criteria) this;
        }

        public Criteria andBeginXEqualTo(Long value) {
            addCriterion("beginX =", value, "beginX");
            return (Criteria) this;
        }

        public Criteria andBeginXNotEqualTo(Long value) {
            addCriterion("beginX <>", value, "beginX");
            return (Criteria) this;
        }

        public Criteria andBeginXGreaterThan(Long value) {
            addCriterion("beginX >", value, "beginX");
            return (Criteria) this;
        }

        public Criteria andBeginXGreaterThanOrEqualTo(Long value) {
            addCriterion("beginX >=", value, "beginX");
            return (Criteria) this;
        }

        public Criteria andBeginXLessThan(Long value) {
            addCriterion("beginX <", value, "beginX");
            return (Criteria) this;
        }

        public Criteria andBeginXLessThanOrEqualTo(Long value) {
            addCriterion("beginX <=", value, "beginX");
            return (Criteria) this;
        }

        public Criteria andBeginXIn(List<Long> values) {
            addCriterion("beginX in", values, "beginX");
            return (Criteria) this;
        }

        public Criteria andBeginXNotIn(List<Long> values) {
            addCriterion("beginX not in", values, "beginX");
            return (Criteria) this;
        }

        public Criteria andBeginXBetween(Long value1, Long value2) {
            addCriterion("beginX between", value1, value2, "beginX");
            return (Criteria) this;
        }

        public Criteria andBeginXNotBetween(Long value1, Long value2) {
            addCriterion("beginX not between", value1, value2, "beginX");
            return (Criteria) this;
        }

        public Criteria andEndXIsNull() {
            addCriterion("endX is null");
            return (Criteria) this;
        }

        public Criteria andEndXIsNotNull() {
            addCriterion("endX is not null");
            return (Criteria) this;
        }

        public Criteria andEndXEqualTo(Long value) {
            addCriterion("endX =", value, "endX");
            return (Criteria) this;
        }

        public Criteria andEndXNotEqualTo(Long value) {
            addCriterion("endX <>", value, "endX");
            return (Criteria) this;
        }

        public Criteria andEndXGreaterThan(Long value) {
            addCriterion("endX >", value, "endX");
            return (Criteria) this;
        }

        public Criteria andEndXGreaterThanOrEqualTo(Long value) {
            addCriterion("endX >=", value, "endX");
            return (Criteria) this;
        }

        public Criteria andEndXLessThan(Long value) {
            addCriterion("endX <", value, "endX");
            return (Criteria) this;
        }

        public Criteria andEndXLessThanOrEqualTo(Long value) {
            addCriterion("endX <=", value, "endX");
            return (Criteria) this;
        }

        public Criteria andEndXIn(List<Long> values) {
            addCriterion("endX in", values, "endX");
            return (Criteria) this;
        }

        public Criteria andEndXNotIn(List<Long> values) {
            addCriterion("endX not in", values, "endX");
            return (Criteria) this;
        }

        public Criteria andEndXBetween(Long value1, Long value2) {
            addCriterion("endX between", value1, value2, "endX");
            return (Criteria) this;
        }

        public Criteria andEndXNotBetween(Long value1, Long value2) {
            addCriterion("endX not between", value1, value2, "endX");
            return (Criteria) this;
        }

        public Criteria andBeginYIsNull() {
            addCriterion("beginY is null");
            return (Criteria) this;
        }

        public Criteria andBeginYIsNotNull() {
            addCriterion("beginY is not null");
            return (Criteria) this;
        }

        public Criteria andBeginYEqualTo(Long value) {
            addCriterion("beginY =", value, "beginY");
            return (Criteria) this;
        }

        public Criteria andBeginYNotEqualTo(Long value) {
            addCriterion("beginY <>", value, "beginY");
            return (Criteria) this;
        }

        public Criteria andBeginYGreaterThan(Long value) {
            addCriterion("beginY >", value, "beginY");
            return (Criteria) this;
        }

        public Criteria andBeginYGreaterThanOrEqualTo(Long value) {
            addCriterion("beginY >=", value, "beginY");
            return (Criteria) this;
        }

        public Criteria andBeginYLessThan(Long value) {
            addCriterion("beginY <", value, "beginY");
            return (Criteria) this;
        }

        public Criteria andBeginYLessThanOrEqualTo(Long value) {
            addCriterion("beginY <=", value, "beginY");
            return (Criteria) this;
        }

        public Criteria andBeginYIn(List<Long> values) {
            addCriterion("beginY in", values, "beginY");
            return (Criteria) this;
        }

        public Criteria andBeginYNotIn(List<Long> values) {
            addCriterion("beginY not in", values, "beginY");
            return (Criteria) this;
        }

        public Criteria andBeginYBetween(Long value1, Long value2) {
            addCriterion("beginY between", value1, value2, "beginY");
            return (Criteria) this;
        }

        public Criteria andBeginYNotBetween(Long value1, Long value2) {
            addCriterion("beginY not between", value1, value2, "beginY");
            return (Criteria) this;
        }

        public Criteria andEndYIsNull() {
            addCriterion("endY is null");
            return (Criteria) this;
        }

        public Criteria andEndYIsNotNull() {
            addCriterion("endY is not null");
            return (Criteria) this;
        }

        public Criteria andEndYEqualTo(Long value) {
            addCriterion("endY =", value, "endY");
            return (Criteria) this;
        }

        public Criteria andEndYNotEqualTo(Long value) {
            addCriterion("endY <>", value, "endY");
            return (Criteria) this;
        }

        public Criteria andEndYGreaterThan(Long value) {
            addCriterion("endY >", value, "endY");
            return (Criteria) this;
        }

        public Criteria andEndYGreaterThanOrEqualTo(Long value) {
            addCriterion("endY >=", value, "endY");
            return (Criteria) this;
        }

        public Criteria andEndYLessThan(Long value) {
            addCriterion("endY <", value, "endY");
            return (Criteria) this;
        }

        public Criteria andEndYLessThanOrEqualTo(Long value) {
            addCriterion("endY <=", value, "endY");
            return (Criteria) this;
        }

        public Criteria andEndYIn(List<Long> values) {
            addCriterion("endY in", values, "endY");
            return (Criteria) this;
        }

        public Criteria andEndYNotIn(List<Long> values) {
            addCriterion("endY not in", values, "endY");
            return (Criteria) this;
        }

        public Criteria andEndYBetween(Long value1, Long value2) {
            addCriterion("endY between", value1, value2, "endY");
            return (Criteria) this;
        }

        public Criteria andEndYNotBetween(Long value1, Long value2) {
            addCriterion("endY not between", value1, value2, "endY");
            return (Criteria) this;
        }

        public Criteria andBeginZIsNull() {
            addCriterion("beginZ is null");
            return (Criteria) this;
        }

        public Criteria andBeginZIsNotNull() {
            addCriterion("beginZ is not null");
            return (Criteria) this;
        }

        public Criteria andBeginZEqualTo(Long value) {
            addCriterion("beginZ =", value, "beginZ");
            return (Criteria) this;
        }

        public Criteria andBeginZNotEqualTo(Long value) {
            addCriterion("beginZ <>", value, "beginZ");
            return (Criteria) this;
        }

        public Criteria andBeginZGreaterThan(Long value) {
            addCriterion("beginZ >", value, "beginZ");
            return (Criteria) this;
        }

        public Criteria andBeginZGreaterThanOrEqualTo(Long value) {
            addCriterion("beginZ >=", value, "beginZ");
            return (Criteria) this;
        }

        public Criteria andBeginZLessThan(Long value) {
            addCriterion("beginZ <", value, "beginZ");
            return (Criteria) this;
        }

        public Criteria andBeginZLessThanOrEqualTo(Long value) {
            addCriterion("beginZ <=", value, "beginZ");
            return (Criteria) this;
        }

        public Criteria andBeginZIn(List<Long> values) {
            addCriterion("beginZ in", values, "beginZ");
            return (Criteria) this;
        }

        public Criteria andBeginZNotIn(List<Long> values) {
            addCriterion("beginZ not in", values, "beginZ");
            return (Criteria) this;
        }

        public Criteria andBeginZBetween(Long value1, Long value2) {
            addCriterion("beginZ between", value1, value2, "beginZ");
            return (Criteria) this;
        }

        public Criteria andBeginZNotBetween(Long value1, Long value2) {
            addCriterion("beginZ not between", value1, value2, "beginZ");
            return (Criteria) this;
        }

        public Criteria andEndZIsNull() {
            addCriterion("endZ is null");
            return (Criteria) this;
        }

        public Criteria andEndZIsNotNull() {
            addCriterion("endZ is not null");
            return (Criteria) this;
        }

        public Criteria andEndZEqualTo(Long value) {
            addCriterion("endZ =", value, "endZ");
            return (Criteria) this;
        }

        public Criteria andEndZNotEqualTo(Long value) {
            addCriterion("endZ <>", value, "endZ");
            return (Criteria) this;
        }

        public Criteria andEndZGreaterThan(Long value) {
            addCriterion("endZ >", value, "endZ");
            return (Criteria) this;
        }

        public Criteria andEndZGreaterThanOrEqualTo(Long value) {
            addCriterion("endZ >=", value, "endZ");
            return (Criteria) this;
        }

        public Criteria andEndZLessThan(Long value) {
            addCriterion("endZ <", value, "endZ");
            return (Criteria) this;
        }

        public Criteria andEndZLessThanOrEqualTo(Long value) {
            addCriterion("endZ <=", value, "endZ");
            return (Criteria) this;
        }

        public Criteria andEndZIn(List<Long> values) {
            addCriterion("endZ in", values, "endZ");
            return (Criteria) this;
        }

        public Criteria andEndZNotIn(List<Long> values) {
            addCriterion("endZ not in", values, "endZ");
            return (Criteria) this;
        }

        public Criteria andEndZBetween(Long value1, Long value2) {
            addCriterion("endZ between", value1, value2, "endZ");
            return (Criteria) this;
        }

        public Criteria andEndZNotBetween(Long value1, Long value2) {
            addCriterion("endZ not between", value1, value2, "endZ");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(String value) {
            addCriterion("is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(String value) {
            addCriterion("is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(String value) {
            addCriterion("is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(String value) {
            addCriterion("is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(String value) {
            addCriterion("is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(String value) {
            addCriterion("is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLike(String value) {
            addCriterion("is_deleted like", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotLike(String value) {
            addCriterion("is_deleted not like", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<String> values) {
            addCriterion("is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<String> values) {
            addCriterion("is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(String value1, String value2) {
            addCriterion("is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(String value1, String value2) {
            addCriterion("is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("update_user like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("update_user not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room_area
     *
     * @mbggenerated do_not_delete_during_merge Fri Feb 09 19:02:10 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room_area
     *
     * @mbggenerated Fri Feb 09 19:02:10 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}