package com.dsw.iot.model;

import com.dsw.iot.util.PageDto;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RoomPropertyDoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room_property
     *
     * @mbggenerated Mon Apr 02 17:35:53 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room_property
     *
     * @mbggenerated Mon Apr 02 17:35:53 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room_property
     *
     * @mbggenerated Mon Apr 02 17:35:53 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room_property
     *
     * @mbggenerated Mon Apr 02 17:35:53 CST 2018
     */
    protected PageDto pageDto;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_property
     *
     * @mbggenerated Mon Apr 02 17:35:53 CST 2018
     */
    public RoomPropertyDoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_property
     *
     * @mbggenerated Mon Apr 02 17:35:53 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_property
     *
     * @mbggenerated Mon Apr 02 17:35:53 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_property
     *
     * @mbggenerated Mon Apr 02 17:35:53 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_property
     *
     * @mbggenerated Mon Apr 02 17:35:53 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_property
     *
     * @mbggenerated Mon Apr 02 17:35:53 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_property
     *
     * @mbggenerated Mon Apr 02 17:35:53 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_property
     *
     * @mbggenerated Mon Apr 02 17:35:53 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_property
     *
     * @mbggenerated Mon Apr 02 17:35:53 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_property
     *
     * @mbggenerated Mon Apr 02 17:35:53 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_property
     *
     * @mbggenerated Mon Apr 02 17:35:53 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_property
     *
     * @mbggenerated Mon Apr 02 17:35:53 CST 2018
     */
    public void setPageDto(PageDto pageDto) {
        this.pageDto=pageDto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_property
     *
     * @mbggenerated Mon Apr 02 17:35:53 CST 2018
     */
    public PageDto getPageDto() {
        return pageDto;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room_property
     *
     * @mbggenerated Mon Apr 02 17:35:53 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrgIsNull() {
            addCriterion("org is null");
            return (Criteria) this;
        }

        public Criteria andOrgIsNotNull() {
            addCriterion("org is not null");
            return (Criteria) this;
        }

        public Criteria andOrgEqualTo(String value) {
            addCriterion("org =", value, "org");
            return (Criteria) this;
        }

        public Criteria andOrgNotEqualTo(String value) {
            addCriterion("org <>", value, "org");
            return (Criteria) this;
        }

        public Criteria andOrgGreaterThan(String value) {
            addCriterion("org >", value, "org");
            return (Criteria) this;
        }

        public Criteria andOrgGreaterThanOrEqualTo(String value) {
            addCriterion("org >=", value, "org");
            return (Criteria) this;
        }

        public Criteria andOrgLessThan(String value) {
            addCriterion("org <", value, "org");
            return (Criteria) this;
        }

        public Criteria andOrgLessThanOrEqualTo(String value) {
            addCriterion("org <=", value, "org");
            return (Criteria) this;
        }

        public Criteria andOrgLike(String value) {
            addCriterion("org like", value, "org");
            return (Criteria) this;
        }

        public Criteria andOrgNotLike(String value) {
            addCriterion("org not like", value, "org");
            return (Criteria) this;
        }

        public Criteria andOrgIn(List<String> values) {
            addCriterion("org in", values, "org");
            return (Criteria) this;
        }

        public Criteria andOrgNotIn(List<String> values) {
            addCriterion("org not in", values, "org");
            return (Criteria) this;
        }

        public Criteria andOrgBetween(String value1, String value2) {
            addCriterion("org between", value1, value2, "org");
            return (Criteria) this;
        }

        public Criteria andOrgNotBetween(String value1, String value2) {
            addCriterion("org not between", value1, value2, "org");
            return (Criteria) this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("area is null");
            return (Criteria) this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("area is not null");
            return (Criteria) this;
        }

        public Criteria andAreaEqualTo(String value) {
            addCriterion("area =", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotEqualTo(String value) {
            addCriterion("area <>", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThan(String value) {
            addCriterion("area >", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(String value) {
            addCriterion("area >=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThan(String value) {
            addCriterion("area <", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThanOrEqualTo(String value) {
            addCriterion("area <=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLike(String value) {
            addCriterion("area like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotLike(String value) {
            addCriterion("area not like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaIn(List<String> values) {
            addCriterion("area in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotIn(List<String> values) {
            addCriterion("area not in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaBetween(String value1, String value2) {
            addCriterion("area between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotBetween(String value1, String value2) {
            addCriterion("area not between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andRoomNameIsNull() {
            addCriterion("room_name is null");
            return (Criteria) this;
        }

        public Criteria andRoomNameIsNotNull() {
            addCriterion("room_name is not null");
            return (Criteria) this;
        }

        public Criteria andRoomNameEqualTo(String value) {
            addCriterion("room_name =", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameNotEqualTo(String value) {
            addCriterion("room_name <>", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameGreaterThan(String value) {
            addCriterion("room_name >", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameGreaterThanOrEqualTo(String value) {
            addCriterion("room_name >=", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameLessThan(String value) {
            addCriterion("room_name <", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameLessThanOrEqualTo(String value) {
            addCriterion("room_name <=", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameLike(String value) {
            addCriterion("room_name like", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameNotLike(String value) {
            addCriterion("room_name not like", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameIn(List<String> values) {
            addCriterion("room_name in", values, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameNotIn(List<String> values) {
            addCriterion("room_name not in", values, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameBetween(String value1, String value2) {
            addCriterion("room_name between", value1, value2, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameNotBetween(String value1, String value2) {
            addCriterion("room_name not between", value1, value2, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNoIsNull() {
            addCriterion("room_no is null");
            return (Criteria) this;
        }

        public Criteria andRoomNoIsNotNull() {
            addCriterion("room_no is not null");
            return (Criteria) this;
        }

        public Criteria andRoomNoEqualTo(String value) {
            addCriterion("room_no =", value, "roomNo");
            return (Criteria) this;
        }

        public Criteria andRoomNoNotEqualTo(String value) {
            addCriterion("room_no <>", value, "roomNo");
            return (Criteria) this;
        }

        public Criteria andRoomNoGreaterThan(String value) {
            addCriterion("room_no >", value, "roomNo");
            return (Criteria) this;
        }

        public Criteria andRoomNoGreaterThanOrEqualTo(String value) {
            addCriterion("room_no >=", value, "roomNo");
            return (Criteria) this;
        }

        public Criteria andRoomNoLessThan(String value) {
            addCriterion("room_no <", value, "roomNo");
            return (Criteria) this;
        }

        public Criteria andRoomNoLessThanOrEqualTo(String value) {
            addCriterion("room_no <=", value, "roomNo");
            return (Criteria) this;
        }

        public Criteria andRoomNoLike(String value) {
            addCriterion("room_no like", value, "roomNo");
            return (Criteria) this;
        }

        public Criteria andRoomNoNotLike(String value) {
            addCriterion("room_no not like", value, "roomNo");
            return (Criteria) this;
        }

        public Criteria andRoomNoIn(List<String> values) {
            addCriterion("room_no in", values, "roomNo");
            return (Criteria) this;
        }

        public Criteria andRoomNoNotIn(List<String> values) {
            addCriterion("room_no not in", values, "roomNo");
            return (Criteria) this;
        }

        public Criteria andRoomNoBetween(String value1, String value2) {
            addCriterion("room_no between", value1, value2, "roomNo");
            return (Criteria) this;
        }

        public Criteria andRoomNoNotBetween(String value1, String value2) {
            addCriterion("room_no not between", value1, value2, "roomNo");
            return (Criteria) this;
        }

        public Criteria andRoomIpIsNull() {
            addCriterion("room_ip is null");
            return (Criteria) this;
        }

        public Criteria andRoomIpIsNotNull() {
            addCriterion("room_ip is not null");
            return (Criteria) this;
        }

        public Criteria andRoomIpEqualTo(String value) {
            addCriterion("room_ip =", value, "roomIp");
            return (Criteria) this;
        }

        public Criteria andRoomIpNotEqualTo(String value) {
            addCriterion("room_ip <>", value, "roomIp");
            return (Criteria) this;
        }

        public Criteria andRoomIpGreaterThan(String value) {
            addCriterion("room_ip >", value, "roomIp");
            return (Criteria) this;
        }

        public Criteria andRoomIpGreaterThanOrEqualTo(String value) {
            addCriterion("room_ip >=", value, "roomIp");
            return (Criteria) this;
        }

        public Criteria andRoomIpLessThan(String value) {
            addCriterion("room_ip <", value, "roomIp");
            return (Criteria) this;
        }

        public Criteria andRoomIpLessThanOrEqualTo(String value) {
            addCriterion("room_ip <=", value, "roomIp");
            return (Criteria) this;
        }

        public Criteria andRoomIpLike(String value) {
            addCriterion("room_ip like", value, "roomIp");
            return (Criteria) this;
        }

        public Criteria andRoomIpNotLike(String value) {
            addCriterion("room_ip not like", value, "roomIp");
            return (Criteria) this;
        }

        public Criteria andRoomIpIn(List<String> values) {
            addCriterion("room_ip in", values, "roomIp");
            return (Criteria) this;
        }

        public Criteria andRoomIpNotIn(List<String> values) {
            addCriterion("room_ip not in", values, "roomIp");
            return (Criteria) this;
        }

        public Criteria andRoomIpBetween(String value1, String value2) {
            addCriterion("room_ip between", value1, value2, "roomIp");
            return (Criteria) this;
        }

        public Criteria andRoomIpNotBetween(String value1, String value2) {
            addCriterion("room_ip not between", value1, value2, "roomIp");
            return (Criteria) this;
        }

        public Criteria andRoomTypeIsNull() {
            addCriterion("room_type is null");
            return (Criteria) this;
        }

        public Criteria andRoomTypeIsNotNull() {
            addCriterion("room_type is not null");
            return (Criteria) this;
        }

        public Criteria andRoomTypeEqualTo(String value) {
            addCriterion("room_type =", value, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeNotEqualTo(String value) {
            addCriterion("room_type <>", value, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeGreaterThan(String value) {
            addCriterion("room_type >", value, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeGreaterThanOrEqualTo(String value) {
            addCriterion("room_type >=", value, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeLessThan(String value) {
            addCriterion("room_type <", value, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeLessThanOrEqualTo(String value) {
            addCriterion("room_type <=", value, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeLike(String value) {
            addCriterion("room_type like", value, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeNotLike(String value) {
            addCriterion("room_type not like", value, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeIn(List<String> values) {
            addCriterion("room_type in", values, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeNotIn(List<String> values) {
            addCriterion("room_type not in", values, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeBetween(String value1, String value2) {
            addCriterion("room_type between", value1, value2, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeNotBetween(String value1, String value2) {
            addCriterion("room_type not between", value1, value2, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomMaxIsNull() {
            addCriterion("room_max is null");
            return (Criteria) this;
        }

        public Criteria andRoomMaxIsNotNull() {
            addCriterion("room_max is not null");
            return (Criteria) this;
        }

        public Criteria andRoomMaxEqualTo(Integer value) {
            addCriterion("room_max =", value, "roomMax");
            return (Criteria) this;
        }

        public Criteria andRoomMaxNotEqualTo(Integer value) {
            addCriterion("room_max <>", value, "roomMax");
            return (Criteria) this;
        }

        public Criteria andRoomMaxGreaterThan(Integer value) {
            addCriterion("room_max >", value, "roomMax");
            return (Criteria) this;
        }

        public Criteria andRoomMaxGreaterThanOrEqualTo(Integer value) {
            addCriterion("room_max >=", value, "roomMax");
            return (Criteria) this;
        }

        public Criteria andRoomMaxLessThan(Integer value) {
            addCriterion("room_max <", value, "roomMax");
            return (Criteria) this;
        }

        public Criteria andRoomMaxLessThanOrEqualTo(Integer value) {
            addCriterion("room_max <=", value, "roomMax");
            return (Criteria) this;
        }

        public Criteria andRoomMaxIn(List<Integer> values) {
            addCriterion("room_max in", values, "roomMax");
            return (Criteria) this;
        }

        public Criteria andRoomMaxNotIn(List<Integer> values) {
            addCriterion("room_max not in", values, "roomMax");
            return (Criteria) this;
        }

        public Criteria andRoomMaxBetween(Integer value1, Integer value2) {
            addCriterion("room_max between", value1, value2, "roomMax");
            return (Criteria) this;
        }

        public Criteria andRoomMaxNotBetween(Integer value1, Integer value2) {
            addCriterion("room_max not between", value1, value2, "roomMax");
            return (Criteria) this;
        }

        public Criteria andRoomStatusIsNull() {
            addCriterion("room_status is null");
            return (Criteria) this;
        }

        public Criteria andRoomStatusIsNotNull() {
            addCriterion("room_status is not null");
            return (Criteria) this;
        }

        public Criteria andRoomStatusEqualTo(String value) {
            addCriterion("room_status =", value, "roomStatus");
            return (Criteria) this;
        }

        public Criteria andRoomStatusNotEqualTo(String value) {
            addCriterion("room_status <>", value, "roomStatus");
            return (Criteria) this;
        }

        public Criteria andRoomStatusGreaterThan(String value) {
            addCriterion("room_status >", value, "roomStatus");
            return (Criteria) this;
        }

        public Criteria andRoomStatusGreaterThanOrEqualTo(String value) {
            addCriterion("room_status >=", value, "roomStatus");
            return (Criteria) this;
        }

        public Criteria andRoomStatusLessThan(String value) {
            addCriterion("room_status <", value, "roomStatus");
            return (Criteria) this;
        }

        public Criteria andRoomStatusLessThanOrEqualTo(String value) {
            addCriterion("room_status <=", value, "roomStatus");
            return (Criteria) this;
        }

        public Criteria andRoomStatusLike(String value) {
            addCriterion("room_status like", value, "roomStatus");
            return (Criteria) this;
        }

        public Criteria andRoomStatusNotLike(String value) {
            addCriterion("room_status not like", value, "roomStatus");
            return (Criteria) this;
        }

        public Criteria andRoomStatusIn(List<String> values) {
            addCriterion("room_status in", values, "roomStatus");
            return (Criteria) this;
        }

        public Criteria andRoomStatusNotIn(List<String> values) {
            addCriterion("room_status not in", values, "roomStatus");
            return (Criteria) this;
        }

        public Criteria andRoomStatusBetween(String value1, String value2) {
            addCriterion("room_status between", value1, value2, "roomStatus");
            return (Criteria) this;
        }

        public Criteria andRoomStatusNotBetween(String value1, String value2) {
            addCriterion("room_status not between", value1, value2, "roomStatus");
            return (Criteria) this;
        }

        public Criteria andLightIpIsNull() {
            addCriterion("light_ip is null");
            return (Criteria) this;
        }

        public Criteria andLightIpIsNotNull() {
            addCriterion("light_ip is not null");
            return (Criteria) this;
        }

        public Criteria andLightIpEqualTo(String value) {
            addCriterion("light_ip =", value, "lightIp");
            return (Criteria) this;
        }

        public Criteria andLightIpNotEqualTo(String value) {
            addCriterion("light_ip <>", value, "lightIp");
            return (Criteria) this;
        }

        public Criteria andLightIpGreaterThan(String value) {
            addCriterion("light_ip >", value, "lightIp");
            return (Criteria) this;
        }

        public Criteria andLightIpGreaterThanOrEqualTo(String value) {
            addCriterion("light_ip >=", value, "lightIp");
            return (Criteria) this;
        }

        public Criteria andLightIpLessThan(String value) {
            addCriterion("light_ip <", value, "lightIp");
            return (Criteria) this;
        }

        public Criteria andLightIpLessThanOrEqualTo(String value) {
            addCriterion("light_ip <=", value, "lightIp");
            return (Criteria) this;
        }

        public Criteria andLightIpLike(String value) {
            addCriterion("light_ip like", value, "lightIp");
            return (Criteria) this;
        }

        public Criteria andLightIpNotLike(String value) {
            addCriterion("light_ip not like", value, "lightIp");
            return (Criteria) this;
        }

        public Criteria andLightIpIn(List<String> values) {
            addCriterion("light_ip in", values, "lightIp");
            return (Criteria) this;
        }

        public Criteria andLightIpNotIn(List<String> values) {
            addCriterion("light_ip not in", values, "lightIp");
            return (Criteria) this;
        }

        public Criteria andLightIpBetween(String value1, String value2) {
            addCriterion("light_ip between", value1, value2, "lightIp");
            return (Criteria) this;
        }

        public Criteria andLightIpNotBetween(String value1, String value2) {
            addCriterion("light_ip not between", value1, value2, "lightIp");
            return (Criteria) this;
        }

        public Criteria andLightPortIsNull() {
            addCriterion("light_port is null");
            return (Criteria) this;
        }

        public Criteria andLightPortIsNotNull() {
            addCriterion("light_port is not null");
            return (Criteria) this;
        }

        public Criteria andLightPortEqualTo(String value) {
            addCriterion("light_port =", value, "lightPort");
            return (Criteria) this;
        }

        public Criteria andLightPortNotEqualTo(String value) {
            addCriterion("light_port <>", value, "lightPort");
            return (Criteria) this;
        }

        public Criteria andLightPortGreaterThan(String value) {
            addCriterion("light_port >", value, "lightPort");
            return (Criteria) this;
        }

        public Criteria andLightPortGreaterThanOrEqualTo(String value) {
            addCriterion("light_port >=", value, "lightPort");
            return (Criteria) this;
        }

        public Criteria andLightPortLessThan(String value) {
            addCriterion("light_port <", value, "lightPort");
            return (Criteria) this;
        }

        public Criteria andLightPortLessThanOrEqualTo(String value) {
            addCriterion("light_port <=", value, "lightPort");
            return (Criteria) this;
        }

        public Criteria andLightPortLike(String value) {
            addCriterion("light_port like", value, "lightPort");
            return (Criteria) this;
        }

        public Criteria andLightPortNotLike(String value) {
            addCriterion("light_port not like", value, "lightPort");
            return (Criteria) this;
        }

        public Criteria andLightPortIn(List<String> values) {
            addCriterion("light_port in", values, "lightPort");
            return (Criteria) this;
        }

        public Criteria andLightPortNotIn(List<String> values) {
            addCriterion("light_port not in", values, "lightPort");
            return (Criteria) this;
        }

        public Criteria andLightPortBetween(String value1, String value2) {
            addCriterion("light_port between", value1, value2, "lightPort");
            return (Criteria) this;
        }

        public Criteria andLightPortNotBetween(String value1, String value2) {
            addCriterion("light_port not between", value1, value2, "lightPort");
            return (Criteria) this;
        }

        public Criteria andLightIndexIsNull() {
            addCriterion("light_index is null");
            return (Criteria) this;
        }

        public Criteria andLightIndexIsNotNull() {
            addCriterion("light_index is not null");
            return (Criteria) this;
        }

        public Criteria andLightIndexEqualTo(Integer value) {
            addCriterion("light_index =", value, "lightIndex");
            return (Criteria) this;
        }

        public Criteria andLightIndexNotEqualTo(Integer value) {
            addCriterion("light_index <>", value, "lightIndex");
            return (Criteria) this;
        }

        public Criteria andLightIndexGreaterThan(Integer value) {
            addCriterion("light_index >", value, "lightIndex");
            return (Criteria) this;
        }

        public Criteria andLightIndexGreaterThanOrEqualTo(Integer value) {
            addCriterion("light_index >=", value, "lightIndex");
            return (Criteria) this;
        }

        public Criteria andLightIndexLessThan(Integer value) {
            addCriterion("light_index <", value, "lightIndex");
            return (Criteria) this;
        }

        public Criteria andLightIndexLessThanOrEqualTo(Integer value) {
            addCriterion("light_index <=", value, "lightIndex");
            return (Criteria) this;
        }

        public Criteria andLightIndexIn(List<Integer> values) {
            addCriterion("light_index in", values, "lightIndex");
            return (Criteria) this;
        }

        public Criteria andLightIndexNotIn(List<Integer> values) {
            addCriterion("light_index not in", values, "lightIndex");
            return (Criteria) this;
        }

        public Criteria andLightIndexBetween(Integer value1, Integer value2) {
            addCriterion("light_index between", value1, value2, "lightIndex");
            return (Criteria) this;
        }

        public Criteria andLightIndexNotBetween(Integer value1, Integer value2) {
            addCriterion("light_index not between", value1, value2, "lightIndex");
            return (Criteria) this;
        }

        public Criteria andLightStatusIsNull() {
            addCriterion("light_status is null");
            return (Criteria) this;
        }

        public Criteria andLightStatusIsNotNull() {
            addCriterion("light_status is not null");
            return (Criteria) this;
        }

        public Criteria andLightStatusEqualTo(String value) {
            addCriterion("light_status =", value, "lightStatus");
            return (Criteria) this;
        }

        public Criteria andLightStatusNotEqualTo(String value) {
            addCriterion("light_status <>", value, "lightStatus");
            return (Criteria) this;
        }

        public Criteria andLightStatusGreaterThan(String value) {
            addCriterion("light_status >", value, "lightStatus");
            return (Criteria) this;
        }

        public Criteria andLightStatusGreaterThanOrEqualTo(String value) {
            addCriterion("light_status >=", value, "lightStatus");
            return (Criteria) this;
        }

        public Criteria andLightStatusLessThan(String value) {
            addCriterion("light_status <", value, "lightStatus");
            return (Criteria) this;
        }

        public Criteria andLightStatusLessThanOrEqualTo(String value) {
            addCriterion("light_status <=", value, "lightStatus");
            return (Criteria) this;
        }

        public Criteria andLightStatusLike(String value) {
            addCriterion("light_status like", value, "lightStatus");
            return (Criteria) this;
        }

        public Criteria andLightStatusNotLike(String value) {
            addCriterion("light_status not like", value, "lightStatus");
            return (Criteria) this;
        }

        public Criteria andLightStatusIn(List<String> values) {
            addCriterion("light_status in", values, "lightStatus");
            return (Criteria) this;
        }

        public Criteria andLightStatusNotIn(List<String> values) {
            addCriterion("light_status not in", values, "lightStatus");
            return (Criteria) this;
        }

        public Criteria andLightStatusBetween(String value1, String value2) {
            addCriterion("light_status between", value1, value2, "lightStatus");
            return (Criteria) this;
        }

        public Criteria andLightStatusNotBetween(String value1, String value2) {
            addCriterion("light_status not between", value1, value2, "lightStatus");
            return (Criteria) this;
        }

        public Criteria andWindIpIsNull() {
            addCriterion("wind_ip is null");
            return (Criteria) this;
        }

        public Criteria andWindIpIsNotNull() {
            addCriterion("wind_ip is not null");
            return (Criteria) this;
        }

        public Criteria andWindIpEqualTo(String value) {
            addCriterion("wind_ip =", value, "windIp");
            return (Criteria) this;
        }

        public Criteria andWindIpNotEqualTo(String value) {
            addCriterion("wind_ip <>", value, "windIp");
            return (Criteria) this;
        }

        public Criteria andWindIpGreaterThan(String value) {
            addCriterion("wind_ip >", value, "windIp");
            return (Criteria) this;
        }

        public Criteria andWindIpGreaterThanOrEqualTo(String value) {
            addCriterion("wind_ip >=", value, "windIp");
            return (Criteria) this;
        }

        public Criteria andWindIpLessThan(String value) {
            addCriterion("wind_ip <", value, "windIp");
            return (Criteria) this;
        }

        public Criteria andWindIpLessThanOrEqualTo(String value) {
            addCriterion("wind_ip <=", value, "windIp");
            return (Criteria) this;
        }

        public Criteria andWindIpLike(String value) {
            addCriterion("wind_ip like", value, "windIp");
            return (Criteria) this;
        }

        public Criteria andWindIpNotLike(String value) {
            addCriterion("wind_ip not like", value, "windIp");
            return (Criteria) this;
        }

        public Criteria andWindIpIn(List<String> values) {
            addCriterion("wind_ip in", values, "windIp");
            return (Criteria) this;
        }

        public Criteria andWindIpNotIn(List<String> values) {
            addCriterion("wind_ip not in", values, "windIp");
            return (Criteria) this;
        }

        public Criteria andWindIpBetween(String value1, String value2) {
            addCriterion("wind_ip between", value1, value2, "windIp");
            return (Criteria) this;
        }

        public Criteria andWindIpNotBetween(String value1, String value2) {
            addCriterion("wind_ip not between", value1, value2, "windIp");
            return (Criteria) this;
        }

        public Criteria andWindPortIsNull() {
            addCriterion("wind_port is null");
            return (Criteria) this;
        }

        public Criteria andWindPortIsNotNull() {
            addCriterion("wind_port is not null");
            return (Criteria) this;
        }

        public Criteria andWindPortEqualTo(String value) {
            addCriterion("wind_port =", value, "windPort");
            return (Criteria) this;
        }

        public Criteria andWindPortNotEqualTo(String value) {
            addCriterion("wind_port <>", value, "windPort");
            return (Criteria) this;
        }

        public Criteria andWindPortGreaterThan(String value) {
            addCriterion("wind_port >", value, "windPort");
            return (Criteria) this;
        }

        public Criteria andWindPortGreaterThanOrEqualTo(String value) {
            addCriterion("wind_port >=", value, "windPort");
            return (Criteria) this;
        }

        public Criteria andWindPortLessThan(String value) {
            addCriterion("wind_port <", value, "windPort");
            return (Criteria) this;
        }

        public Criteria andWindPortLessThanOrEqualTo(String value) {
            addCriterion("wind_port <=", value, "windPort");
            return (Criteria) this;
        }

        public Criteria andWindPortLike(String value) {
            addCriterion("wind_port like", value, "windPort");
            return (Criteria) this;
        }

        public Criteria andWindPortNotLike(String value) {
            addCriterion("wind_port not like", value, "windPort");
            return (Criteria) this;
        }

        public Criteria andWindPortIn(List<String> values) {
            addCriterion("wind_port in", values, "windPort");
            return (Criteria) this;
        }

        public Criteria andWindPortNotIn(List<String> values) {
            addCriterion("wind_port not in", values, "windPort");
            return (Criteria) this;
        }

        public Criteria andWindPortBetween(String value1, String value2) {
            addCriterion("wind_port between", value1, value2, "windPort");
            return (Criteria) this;
        }

        public Criteria andWindPortNotBetween(String value1, String value2) {
            addCriterion("wind_port not between", value1, value2, "windPort");
            return (Criteria) this;
        }

        public Criteria andWindRoadIsNull() {
            addCriterion("wind_road is null");
            return (Criteria) this;
        }

        public Criteria andWindRoadIsNotNull() {
            addCriterion("wind_road is not null");
            return (Criteria) this;
        }

        public Criteria andWindRoadEqualTo(Integer value) {
            addCriterion("wind_road =", value, "windRoad");
            return (Criteria) this;
        }

        public Criteria andWindRoadNotEqualTo(Integer value) {
            addCriterion("wind_road <>", value, "windRoad");
            return (Criteria) this;
        }

        public Criteria andWindRoadGreaterThan(Integer value) {
            addCriterion("wind_road >", value, "windRoad");
            return (Criteria) this;
        }

        public Criteria andWindRoadGreaterThanOrEqualTo(Integer value) {
            addCriterion("wind_road >=", value, "windRoad");
            return (Criteria) this;
        }

        public Criteria andWindRoadLessThan(Integer value) {
            addCriterion("wind_road <", value, "windRoad");
            return (Criteria) this;
        }

        public Criteria andWindRoadLessThanOrEqualTo(Integer value) {
            addCriterion("wind_road <=", value, "windRoad");
            return (Criteria) this;
        }

        public Criteria andWindRoadIn(List<Integer> values) {
            addCriterion("wind_road in", values, "windRoad");
            return (Criteria) this;
        }

        public Criteria andWindRoadNotIn(List<Integer> values) {
            addCriterion("wind_road not in", values, "windRoad");
            return (Criteria) this;
        }

        public Criteria andWindRoadBetween(Integer value1, Integer value2) {
            addCriterion("wind_road between", value1, value2, "windRoad");
            return (Criteria) this;
        }

        public Criteria andWindRoadNotBetween(Integer value1, Integer value2) {
            addCriterion("wind_road not between", value1, value2, "windRoad");
            return (Criteria) this;
        }

        public Criteria andWindStatusIsNull() {
            addCriterion("wind_status is null");
            return (Criteria) this;
        }

        public Criteria andWindStatusIsNotNull() {
            addCriterion("wind_status is not null");
            return (Criteria) this;
        }

        public Criteria andWindStatusEqualTo(String value) {
            addCriterion("wind_status =", value, "windStatus");
            return (Criteria) this;
        }

        public Criteria andWindStatusNotEqualTo(String value) {
            addCriterion("wind_status <>", value, "windStatus");
            return (Criteria) this;
        }

        public Criteria andWindStatusGreaterThan(String value) {
            addCriterion("wind_status >", value, "windStatus");
            return (Criteria) this;
        }

        public Criteria andWindStatusGreaterThanOrEqualTo(String value) {
            addCriterion("wind_status >=", value, "windStatus");
            return (Criteria) this;
        }

        public Criteria andWindStatusLessThan(String value) {
            addCriterion("wind_status <", value, "windStatus");
            return (Criteria) this;
        }

        public Criteria andWindStatusLessThanOrEqualTo(String value) {
            addCriterion("wind_status <=", value, "windStatus");
            return (Criteria) this;
        }

        public Criteria andWindStatusLike(String value) {
            addCriterion("wind_status like", value, "windStatus");
            return (Criteria) this;
        }

        public Criteria andWindStatusNotLike(String value) {
            addCriterion("wind_status not like", value, "windStatus");
            return (Criteria) this;
        }

        public Criteria andWindStatusIn(List<String> values) {
            addCriterion("wind_status in", values, "windStatus");
            return (Criteria) this;
        }

        public Criteria andWindStatusNotIn(List<String> values) {
            addCriterion("wind_status not in", values, "windStatus");
            return (Criteria) this;
        }

        public Criteria andWindStatusBetween(String value1, String value2) {
            addCriterion("wind_status between", value1, value2, "windStatus");
            return (Criteria) this;
        }

        public Criteria andWindStatusNotBetween(String value1, String value2) {
            addCriterion("wind_status not between", value1, value2, "windStatus");
            return (Criteria) this;
        }

        public Criteria andWallIpIsNull() {
            addCriterion("wall_ip is null");
            return (Criteria) this;
        }

        public Criteria andWallIpIsNotNull() {
            addCriterion("wall_ip is not null");
            return (Criteria) this;
        }

        public Criteria andWallIpEqualTo(String value) {
            addCriterion("wall_ip =", value, "wallIp");
            return (Criteria) this;
        }

        public Criteria andWallIpNotEqualTo(String value) {
            addCriterion("wall_ip <>", value, "wallIp");
            return (Criteria) this;
        }

        public Criteria andWallIpGreaterThan(String value) {
            addCriterion("wall_ip >", value, "wallIp");
            return (Criteria) this;
        }

        public Criteria andWallIpGreaterThanOrEqualTo(String value) {
            addCriterion("wall_ip >=", value, "wallIp");
            return (Criteria) this;
        }

        public Criteria andWallIpLessThan(String value) {
            addCriterion("wall_ip <", value, "wallIp");
            return (Criteria) this;
        }

        public Criteria andWallIpLessThanOrEqualTo(String value) {
            addCriterion("wall_ip <=", value, "wallIp");
            return (Criteria) this;
        }

        public Criteria andWallIpLike(String value) {
            addCriterion("wall_ip like", value, "wallIp");
            return (Criteria) this;
        }

        public Criteria andWallIpNotLike(String value) {
            addCriterion("wall_ip not like", value, "wallIp");
            return (Criteria) this;
        }

        public Criteria andWallIpIn(List<String> values) {
            addCriterion("wall_ip in", values, "wallIp");
            return (Criteria) this;
        }

        public Criteria andWallIpNotIn(List<String> values) {
            addCriterion("wall_ip not in", values, "wallIp");
            return (Criteria) this;
        }

        public Criteria andWallIpBetween(String value1, String value2) {
            addCriterion("wall_ip between", value1, value2, "wallIp");
            return (Criteria) this;
        }

        public Criteria andWallIpNotBetween(String value1, String value2) {
            addCriterion("wall_ip not between", value1, value2, "wallIp");
            return (Criteria) this;
        }

        public Criteria andWallPortIsNull() {
            addCriterion("wall_port is null");
            return (Criteria) this;
        }

        public Criteria andWallPortIsNotNull() {
            addCriterion("wall_port is not null");
            return (Criteria) this;
        }

        public Criteria andWallPortEqualTo(String value) {
            addCriterion("wall_port =", value, "wallPort");
            return (Criteria) this;
        }

        public Criteria andWallPortNotEqualTo(String value) {
            addCriterion("wall_port <>", value, "wallPort");
            return (Criteria) this;
        }

        public Criteria andWallPortGreaterThan(String value) {
            addCriterion("wall_port >", value, "wallPort");
            return (Criteria) this;
        }

        public Criteria andWallPortGreaterThanOrEqualTo(String value) {
            addCriterion("wall_port >=", value, "wallPort");
            return (Criteria) this;
        }

        public Criteria andWallPortLessThan(String value) {
            addCriterion("wall_port <", value, "wallPort");
            return (Criteria) this;
        }

        public Criteria andWallPortLessThanOrEqualTo(String value) {
            addCriterion("wall_port <=", value, "wallPort");
            return (Criteria) this;
        }

        public Criteria andWallPortLike(String value) {
            addCriterion("wall_port like", value, "wallPort");
            return (Criteria) this;
        }

        public Criteria andWallPortNotLike(String value) {
            addCriterion("wall_port not like", value, "wallPort");
            return (Criteria) this;
        }

        public Criteria andWallPortIn(List<String> values) {
            addCriterion("wall_port in", values, "wallPort");
            return (Criteria) this;
        }

        public Criteria andWallPortNotIn(List<String> values) {
            addCriterion("wall_port not in", values, "wallPort");
            return (Criteria) this;
        }

        public Criteria andWallPortBetween(String value1, String value2) {
            addCriterion("wall_port between", value1, value2, "wallPort");
            return (Criteria) this;
        }

        public Criteria andWallPortNotBetween(String value1, String value2) {
            addCriterion("wall_port not between", value1, value2, "wallPort");
            return (Criteria) this;
        }

        public Criteria andWallRoadIsNull() {
            addCriterion("wall_road is null");
            return (Criteria) this;
        }

        public Criteria andWallRoadIsNotNull() {
            addCriterion("wall_road is not null");
            return (Criteria) this;
        }

        public Criteria andWallRoadEqualTo(Integer value) {
            addCriterion("wall_road =", value, "wallRoad");
            return (Criteria) this;
        }

        public Criteria andWallRoadNotEqualTo(Integer value) {
            addCriterion("wall_road <>", value, "wallRoad");
            return (Criteria) this;
        }

        public Criteria andWallRoadGreaterThan(Integer value) {
            addCriterion("wall_road >", value, "wallRoad");
            return (Criteria) this;
        }

        public Criteria andWallRoadGreaterThanOrEqualTo(Integer value) {
            addCriterion("wall_road >=", value, "wallRoad");
            return (Criteria) this;
        }

        public Criteria andWallRoadLessThan(Integer value) {
            addCriterion("wall_road <", value, "wallRoad");
            return (Criteria) this;
        }

        public Criteria andWallRoadLessThanOrEqualTo(Integer value) {
            addCriterion("wall_road <=", value, "wallRoad");
            return (Criteria) this;
        }

        public Criteria andWallRoadIn(List<Integer> values) {
            addCriterion("wall_road in", values, "wallRoad");
            return (Criteria) this;
        }

        public Criteria andWallRoadNotIn(List<Integer> values) {
            addCriterion("wall_road not in", values, "wallRoad");
            return (Criteria) this;
        }

        public Criteria andWallRoadBetween(Integer value1, Integer value2) {
            addCriterion("wall_road between", value1, value2, "wallRoad");
            return (Criteria) this;
        }

        public Criteria andWallRoadNotBetween(Integer value1, Integer value2) {
            addCriterion("wall_road not between", value1, value2, "wallRoad");
            return (Criteria) this;
        }

        public Criteria andWallStatusIsNull() {
            addCriterion("wall_status is null");
            return (Criteria) this;
        }

        public Criteria andWallStatusIsNotNull() {
            addCriterion("wall_status is not null");
            return (Criteria) this;
        }

        public Criteria andWallStatusEqualTo(String value) {
            addCriterion("wall_status =", value, "wallStatus");
            return (Criteria) this;
        }

        public Criteria andWallStatusNotEqualTo(String value) {
            addCriterion("wall_status <>", value, "wallStatus");
            return (Criteria) this;
        }

        public Criteria andWallStatusGreaterThan(String value) {
            addCriterion("wall_status >", value, "wallStatus");
            return (Criteria) this;
        }

        public Criteria andWallStatusGreaterThanOrEqualTo(String value) {
            addCriterion("wall_status >=", value, "wallStatus");
            return (Criteria) this;
        }

        public Criteria andWallStatusLessThan(String value) {
            addCriterion("wall_status <", value, "wallStatus");
            return (Criteria) this;
        }

        public Criteria andWallStatusLessThanOrEqualTo(String value) {
            addCriterion("wall_status <=", value, "wallStatus");
            return (Criteria) this;
        }

        public Criteria andWallStatusLike(String value) {
            addCriterion("wall_status like", value, "wallStatus");
            return (Criteria) this;
        }

        public Criteria andWallStatusNotLike(String value) {
            addCriterion("wall_status not like", value, "wallStatus");
            return (Criteria) this;
        }

        public Criteria andWallStatusIn(List<String> values) {
            addCriterion("wall_status in", values, "wallStatus");
            return (Criteria) this;
        }

        public Criteria andWallStatusNotIn(List<String> values) {
            addCriterion("wall_status not in", values, "wallStatus");
            return (Criteria) this;
        }

        public Criteria andWallStatusBetween(String value1, String value2) {
            addCriterion("wall_status between", value1, value2, "wallStatus");
            return (Criteria) this;
        }

        public Criteria andWallStatusNotBetween(String value1, String value2) {
            addCriterion("wall_status not between", value1, value2, "wallStatus");
            return (Criteria) this;
        }

        public Criteria andLedIpIsNull() {
            addCriterion("led_ip is null");
            return (Criteria) this;
        }

        public Criteria andLedIpIsNotNull() {
            addCriterion("led_ip is not null");
            return (Criteria) this;
        }

        public Criteria andLedIpEqualTo(String value) {
            addCriterion("led_ip =", value, "ledIp");
            return (Criteria) this;
        }

        public Criteria andLedIpNotEqualTo(String value) {
            addCriterion("led_ip <>", value, "ledIp");
            return (Criteria) this;
        }

        public Criteria andLedIpGreaterThan(String value) {
            addCriterion("led_ip >", value, "ledIp");
            return (Criteria) this;
        }

        public Criteria andLedIpGreaterThanOrEqualTo(String value) {
            addCriterion("led_ip >=", value, "ledIp");
            return (Criteria) this;
        }

        public Criteria andLedIpLessThan(String value) {
            addCriterion("led_ip <", value, "ledIp");
            return (Criteria) this;
        }

        public Criteria andLedIpLessThanOrEqualTo(String value) {
            addCriterion("led_ip <=", value, "ledIp");
            return (Criteria) this;
        }

        public Criteria andLedIpLike(String value) {
            addCriterion("led_ip like", value, "ledIp");
            return (Criteria) this;
        }

        public Criteria andLedIpNotLike(String value) {
            addCriterion("led_ip not like", value, "ledIp");
            return (Criteria) this;
        }

        public Criteria andLedIpIn(List<String> values) {
            addCriterion("led_ip in", values, "ledIp");
            return (Criteria) this;
        }

        public Criteria andLedIpNotIn(List<String> values) {
            addCriterion("led_ip not in", values, "ledIp");
            return (Criteria) this;
        }

        public Criteria andLedIpBetween(String value1, String value2) {
            addCriterion("led_ip between", value1, value2, "ledIp");
            return (Criteria) this;
        }

        public Criteria andLedIpNotBetween(String value1, String value2) {
            addCriterion("led_ip not between", value1, value2, "ledIp");
            return (Criteria) this;
        }

        public Criteria andLedPortIsNull() {
            addCriterion("led_port is null");
            return (Criteria) this;
        }

        public Criteria andLedPortIsNotNull() {
            addCriterion("led_port is not null");
            return (Criteria) this;
        }

        public Criteria andLedPortEqualTo(String value) {
            addCriterion("led_port =", value, "ledPort");
            return (Criteria) this;
        }

        public Criteria andLedPortNotEqualTo(String value) {
            addCriterion("led_port <>", value, "ledPort");
            return (Criteria) this;
        }

        public Criteria andLedPortGreaterThan(String value) {
            addCriterion("led_port >", value, "ledPort");
            return (Criteria) this;
        }

        public Criteria andLedPortGreaterThanOrEqualTo(String value) {
            addCriterion("led_port >=", value, "ledPort");
            return (Criteria) this;
        }

        public Criteria andLedPortLessThan(String value) {
            addCriterion("led_port <", value, "ledPort");
            return (Criteria) this;
        }

        public Criteria andLedPortLessThanOrEqualTo(String value) {
            addCriterion("led_port <=", value, "ledPort");
            return (Criteria) this;
        }

        public Criteria andLedPortLike(String value) {
            addCriterion("led_port like", value, "ledPort");
            return (Criteria) this;
        }

        public Criteria andLedPortNotLike(String value) {
            addCriterion("led_port not like", value, "ledPort");
            return (Criteria) this;
        }

        public Criteria andLedPortIn(List<String> values) {
            addCriterion("led_port in", values, "ledPort");
            return (Criteria) this;
        }

        public Criteria andLedPortNotIn(List<String> values) {
            addCriterion("led_port not in", values, "ledPort");
            return (Criteria) this;
        }

        public Criteria andLedPortBetween(String value1, String value2) {
            addCriterion("led_port between", value1, value2, "ledPort");
            return (Criteria) this;
        }

        public Criteria andLedPortNotBetween(String value1, String value2) {
            addCriterion("led_port not between", value1, value2, "ledPort");
            return (Criteria) this;
        }

        public Criteria andLedRoadIsNull() {
            addCriterion("led_road is null");
            return (Criteria) this;
        }

        public Criteria andLedRoadIsNotNull() {
            addCriterion("led_road is not null");
            return (Criteria) this;
        }

        public Criteria andLedRoadEqualTo(Integer value) {
            addCriterion("led_road =", value, "ledRoad");
            return (Criteria) this;
        }

        public Criteria andLedRoadNotEqualTo(Integer value) {
            addCriterion("led_road <>", value, "ledRoad");
            return (Criteria) this;
        }

        public Criteria andLedRoadGreaterThan(Integer value) {
            addCriterion("led_road >", value, "ledRoad");
            return (Criteria) this;
        }

        public Criteria andLedRoadGreaterThanOrEqualTo(Integer value) {
            addCriterion("led_road >=", value, "ledRoad");
            return (Criteria) this;
        }

        public Criteria andLedRoadLessThan(Integer value) {
            addCriterion("led_road <", value, "ledRoad");
            return (Criteria) this;
        }

        public Criteria andLedRoadLessThanOrEqualTo(Integer value) {
            addCriterion("led_road <=", value, "ledRoad");
            return (Criteria) this;
        }

        public Criteria andLedRoadIn(List<Integer> values) {
            addCriterion("led_road in", values, "ledRoad");
            return (Criteria) this;
        }

        public Criteria andLedRoadNotIn(List<Integer> values) {
            addCriterion("led_road not in", values, "ledRoad");
            return (Criteria) this;
        }

        public Criteria andLedRoadBetween(Integer value1, Integer value2) {
            addCriterion("led_road between", value1, value2, "ledRoad");
            return (Criteria) this;
        }

        public Criteria andLedRoadNotBetween(Integer value1, Integer value2) {
            addCriterion("led_road not between", value1, value2, "ledRoad");
            return (Criteria) this;
        }

        public Criteria andLedStatusIsNull() {
            addCriterion("led_status is null");
            return (Criteria) this;
        }

        public Criteria andLedStatusIsNotNull() {
            addCriterion("led_status is not null");
            return (Criteria) this;
        }

        public Criteria andLedStatusEqualTo(String value) {
            addCriterion("led_status =", value, "ledStatus");
            return (Criteria) this;
        }

        public Criteria andLedStatusNotEqualTo(String value) {
            addCriterion("led_status <>", value, "ledStatus");
            return (Criteria) this;
        }

        public Criteria andLedStatusGreaterThan(String value) {
            addCriterion("led_status >", value, "ledStatus");
            return (Criteria) this;
        }

        public Criteria andLedStatusGreaterThanOrEqualTo(String value) {
            addCriterion("led_status >=", value, "ledStatus");
            return (Criteria) this;
        }

        public Criteria andLedStatusLessThan(String value) {
            addCriterion("led_status <", value, "ledStatus");
            return (Criteria) this;
        }

        public Criteria andLedStatusLessThanOrEqualTo(String value) {
            addCriterion("led_status <=", value, "ledStatus");
            return (Criteria) this;
        }

        public Criteria andLedStatusLike(String value) {
            addCriterion("led_status like", value, "ledStatus");
            return (Criteria) this;
        }

        public Criteria andLedStatusNotLike(String value) {
            addCriterion("led_status not like", value, "ledStatus");
            return (Criteria) this;
        }

        public Criteria andLedStatusIn(List<String> values) {
            addCriterion("led_status in", values, "ledStatus");
            return (Criteria) this;
        }

        public Criteria andLedStatusNotIn(List<String> values) {
            addCriterion("led_status not in", values, "ledStatus");
            return (Criteria) this;
        }

        public Criteria andLedStatusBetween(String value1, String value2) {
            addCriterion("led_status between", value1, value2, "ledStatus");
            return (Criteria) this;
        }

        public Criteria andLedStatusNotBetween(String value1, String value2) {
            addCriterion("led_status not between", value1, value2, "ledStatus");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(String value) {
            addCriterion("is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(String value) {
            addCriterion("is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(String value) {
            addCriterion("is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(String value) {
            addCriterion("is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(String value) {
            addCriterion("is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(String value) {
            addCriterion("is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLike(String value) {
            addCriterion("is_deleted like", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotLike(String value) {
            addCriterion("is_deleted not like", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<String> values) {
            addCriterion("is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<String> values) {
            addCriterion("is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(String value1, String value2) {
            addCriterion("is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(String value1, String value2) {
            addCriterion("is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("update_user like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("update_user not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room_property
     *
     * @mbggenerated do_not_delete_during_merge Mon Apr 02 17:35:53 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room_property
     *
     * @mbggenerated Mon Apr 02 17:35:53 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}