package com.dsw.iot.model;

public class SwytCjDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWYT_CJ.CJBH
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    private String cjbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWYT_CJ.JJBH
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    private String jjbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWYT_CJ.BJXS
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    private String bjxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWYT_CJ.BJRLXFS
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    private String bjrlxfs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWYT_CJ.CJJG
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    private String cjjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWYT_CJ.CJDW
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    private String cjdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWYT_CJ.CJR
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    private String cjr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWYT_CJ.CJRQSJ
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    private String cjrqsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWYT_CJ.CJDDXZ
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    private String cjddxz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWYT_CJ.CJXXQK
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    private String cjxxqk;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWYT_CJ.CJBH
     *
     * @return the value of SWYT_CJ.CJBH
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    public String getCjbh() {
        return cjbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWYT_CJ.CJBH
     *
     * @param cjbh the value for SWYT_CJ.CJBH
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    public void setCjbh(String cjbh) {
        this.cjbh = cjbh == null ? null : cjbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWYT_CJ.JJBH
     *
     * @return the value of SWYT_CJ.JJBH
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    public String getJjbh() {
        return jjbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWYT_CJ.JJBH
     *
     * @param jjbh the value for SWYT_CJ.JJBH
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    public void setJjbh(String jjbh) {
        this.jjbh = jjbh == null ? null : jjbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWYT_CJ.BJXS
     *
     * @return the value of SWYT_CJ.BJXS
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    public String getBjxs() {
        return bjxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWYT_CJ.BJXS
     *
     * @param bjxs the value for SWYT_CJ.BJXS
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    public void setBjxs(String bjxs) {
        this.bjxs = bjxs == null ? null : bjxs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWYT_CJ.BJRLXFS
     *
     * @return the value of SWYT_CJ.BJRLXFS
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    public String getBjrlxfs() {
        return bjrlxfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWYT_CJ.BJRLXFS
     *
     * @param bjrlxfs the value for SWYT_CJ.BJRLXFS
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    public void setBjrlxfs(String bjrlxfs) {
        this.bjrlxfs = bjrlxfs == null ? null : bjrlxfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWYT_CJ.CJJG
     *
     * @return the value of SWYT_CJ.CJJG
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    public String getCjjg() {
        return cjjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWYT_CJ.CJJG
     *
     * @param cjjg the value for SWYT_CJ.CJJG
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    public void setCjjg(String cjjg) {
        this.cjjg = cjjg == null ? null : cjjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWYT_CJ.CJDW
     *
     * @return the value of SWYT_CJ.CJDW
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    public String getCjdw() {
        return cjdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWYT_CJ.CJDW
     *
     * @param cjdw the value for SWYT_CJ.CJDW
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    public void setCjdw(String cjdw) {
        this.cjdw = cjdw == null ? null : cjdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWYT_CJ.CJR
     *
     * @return the value of SWYT_CJ.CJR
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    public String getCjr() {
        return cjr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWYT_CJ.CJR
     *
     * @param cjr the value for SWYT_CJ.CJR
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    public void setCjr(String cjr) {
        this.cjr = cjr == null ? null : cjr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWYT_CJ.CJRQSJ
     *
     * @return the value of SWYT_CJ.CJRQSJ
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    public String getCjrqsj() {
        return cjrqsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWYT_CJ.CJRQSJ
     *
     * @param cjrqsj the value for SWYT_CJ.CJRQSJ
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    public void setCjrqsj(String cjrqsj) {
        this.cjrqsj = cjrqsj == null ? null : cjrqsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWYT_CJ.CJDDXZ
     *
     * @return the value of SWYT_CJ.CJDDXZ
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    public String getCjddxz() {
        return cjddxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWYT_CJ.CJDDXZ
     *
     * @param cjddxz the value for SWYT_CJ.CJDDXZ
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    public void setCjddxz(String cjddxz) {
        this.cjddxz = cjddxz == null ? null : cjddxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWYT_CJ.CJXXQK
     *
     * @return the value of SWYT_CJ.CJXXQK
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    public String getCjxxqk() {
        return cjxxqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWYT_CJ.CJXXQK
     *
     * @param cjxxqk the value for SWYT_CJ.CJXXQK
     *
     * @mbggenerated Wed May 02 13:36:13 CST 2018
     */
    public void setCjxxqk(String cjxxqk) {
        this.cjxxqk = cjxxqk == null ? null : cjxxqk.trim();
    }
}