package com.dsw.iot.model;

import java.util.Date;

public class SystemConfDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.id
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.key_info
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    private String keyInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.title
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.content
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.status
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.is_deleted
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.create_time
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.create_user
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.update_time
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.update_user
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.message_value
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    private String messageValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.id
     *
     * @return the value of system_config.id
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.id
     *
     * @param id the value for system_config.id
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.key_info
     *
     * @return the value of system_config.key_info
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    public String getKeyInfo() {
        return keyInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.key_info
     *
     * @param keyInfo the value for system_config.key_info
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    public void setKeyInfo(String keyInfo) {
        this.keyInfo = keyInfo == null ? null : keyInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.title
     *
     * @return the value of system_config.title
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.title
     *
     * @param title the value for system_config.title
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.content
     *
     * @return the value of system_config.content
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.content
     *
     * @param content the value for system_config.content
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.status
     *
     * @return the value of system_config.status
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.status
     *
     * @param status the value for system_config.status
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.is_deleted
     *
     * @return the value of system_config.is_deleted
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.is_deleted
     *
     * @param isDeleted the value for system_config.is_deleted
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.create_time
     *
     * @return the value of system_config.create_time
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.create_time
     *
     * @param createTime the value for system_config.create_time
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.create_user
     *
     * @return the value of system_config.create_user
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.create_user
     *
     * @param createUser the value for system_config.create_user
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.update_time
     *
     * @return the value of system_config.update_time
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.update_time
     *
     * @param updateTime the value for system_config.update_time
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.update_user
     *
     * @return the value of system_config.update_user
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.update_user
     *
     * @param updateUser the value for system_config.update_user
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.message_value
     *
     * @return the value of system_config.message_value
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    public String getMessageValue() {
        return messageValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.message_value
     *
     * @param messageValue the value for system_config.message_value
     *
     * @mbggenerated Tue Apr 03 12:24:46 CST 2018
     */
    public void setMessageValue(String messageValue) {
        this.messageValue = messageValue == null ? null : messageValue.trim();
    }
}