package com.dsw.iot.model;

import java.util.Date;

public class TpBaqryUserDo {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.id
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.credicard
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String credicard;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.credicard_type
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String credicardType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.username
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.othername
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String othername;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.sex
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.pastname
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String pastname;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.birthday
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.phone
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.nickname
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.domicile_country
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String domicileCountry;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.current_country
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String currentCountry;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.education_level
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String educationLevel;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.nationality
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String nationality;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.political
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String political;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.national
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String national;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.work_units
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String workUnits;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.out_time
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String outTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.in_time
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private Date inTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.accomplices_way
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String accomplicesWay;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.handling_area
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String handlingArea;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.accomplices_reason
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String accomplicesReason;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.special_group
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String specialGroup;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.person_type
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String personType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.police_name
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String policeName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.handing_place
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String handingPlace;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.storage_tag
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String storageTag;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.bracelet_number
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String braceletNumber;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.storage_number
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String storageNumber;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.is_warned
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String isWarned;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.alert_number
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String alertNumber;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.word_number
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String wordNumber;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.medical_history
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String medicalHistory;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.check_result
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String checkResult;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.material_path
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String materialPath;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.goods_photo
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String goodsPhoto;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.wait_room
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String waitRoom;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.acquisition_project
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String acquisitionProject;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.is_check
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String isCheck;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.out_reason
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String outReason;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.attachment
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String attachment;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.person_status
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String personStatus;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.attachment_url
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String attachmentUrl;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.police_sign
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String policeSign;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.witness_sign
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String witnessSign;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.checked_sign
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String checkedSign;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.sponsor_sign
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String sponsorSign;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.controll_sign
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String controllSign;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.involved_sign
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String involvedSign;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.admin_sign
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String adminSign;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.onpolice_sign
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String onpoliceSign;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.take_sign
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String takeSign;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.yqgy
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String yqgy;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.picture
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.in_camera
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String inCamera;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.out_camera
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String outCamera;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.update_date
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.s
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String s;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.hd0
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String hd0;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.bz0
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String bz0;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.hd1
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String hd1;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.bz1
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String bz1;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.sign1
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String sign1;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.sign2
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String sign2;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.cd_check
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String cdCheck;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.cd_code
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String cdCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.sftype
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String sftype;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.ajtype
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String ajtype;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tp_baqry_user.ystime
     *
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    private String ystime;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.id
     *
     * @return the value of tp_baqry_user.id
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.id
     *
     * @param id the value for tp_baqry_user.id
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.credicard
     *
     * @return the value of tp_baqry_user.credicard
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getCredicard() {
        return credicard;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.credicard
     *
     * @param credicard the value for tp_baqry_user.credicard
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setCredicard(String credicard) {
        this.credicard = credicard == null ? null : credicard.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.credicard_type
     *
     * @return the value of tp_baqry_user.credicard_type
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getCredicardType() {
        return credicardType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.credicard_type
     *
     * @param credicardType the value for tp_baqry_user.credicard_type
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setCredicardType(String credicardType) {
        this.credicardType = credicardType == null ? null : credicardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.username
     *
     * @return the value of tp_baqry_user.username
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.username
     *
     * @param username the value for tp_baqry_user.username
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.othername
     *
     * @return the value of tp_baqry_user.othername
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getOthername() {
        return othername;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.othername
     *
     * @param othername the value for tp_baqry_user.othername
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setOthername(String othername) {
        this.othername = othername == null ? null : othername.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.sex
     *
     * @return the value of tp_baqry_user.sex
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.sex
     *
     * @param sex the value for tp_baqry_user.sex
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.pastname
     *
     * @return the value of tp_baqry_user.pastname
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getPastname() {
        return pastname;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.pastname
     *
     * @param pastname the value for tp_baqry_user.pastname
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setPastname(String pastname) {
        this.pastname = pastname == null ? null : pastname.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.birthday
     *
     * @return the value of tp_baqry_user.birthday
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.birthday
     *
     * @param birthday the value for tp_baqry_user.birthday
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.phone
     *
     * @return the value of tp_baqry_user.phone
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.phone
     *
     * @param phone the value for tp_baqry_user.phone
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.nickname
     *
     * @return the value of tp_baqry_user.nickname
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.nickname
     *
     * @param nickname the value for tp_baqry_user.nickname
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.domicile_country
     *
     * @return the value of tp_baqry_user.domicile_country
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getDomicileCountry() {
        return domicileCountry;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.domicile_country
     *
     * @param domicileCountry the value for tp_baqry_user.domicile_country
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setDomicileCountry(String domicileCountry) {
        this.domicileCountry = domicileCountry == null ? null : domicileCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.current_country
     *
     * @return the value of tp_baqry_user.current_country
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getCurrentCountry() {
        return currentCountry;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.current_country
     *
     * @param currentCountry the value for tp_baqry_user.current_country
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setCurrentCountry(String currentCountry) {
        this.currentCountry = currentCountry == null ? null : currentCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.education_level
     *
     * @return the value of tp_baqry_user.education_level
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getEducationLevel() {
        return educationLevel;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.education_level
     *
     * @param educationLevel the value for tp_baqry_user.education_level
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setEducationLevel(String educationLevel) {
        this.educationLevel = educationLevel == null ? null : educationLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.nationality
     *
     * @return the value of tp_baqry_user.nationality
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.nationality
     *
     * @param nationality the value for tp_baqry_user.nationality
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setNationality(String nationality) {
        this.nationality = nationality == null ? null : nationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.political
     *
     * @return the value of tp_baqry_user.political
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getPolitical() {
        return political;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.political
     *
     * @param political the value for tp_baqry_user.political
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setPolitical(String political) {
        this.political = political == null ? null : political.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.national
     *
     * @return the value of tp_baqry_user.national
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getNational() {
        return national;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.national
     *
     * @param national the value for tp_baqry_user.national
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setNational(String national) {
        this.national = national == null ? null : national.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.work_units
     *
     * @return the value of tp_baqry_user.work_units
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getWorkUnits() {
        return workUnits;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.work_units
     *
     * @param workUnits the value for tp_baqry_user.work_units
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setWorkUnits(String workUnits) {
        this.workUnits = workUnits == null ? null : workUnits.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.out_time
     *
     * @return the value of tp_baqry_user.out_time
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getOutTime() {
        return outTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.out_time
     *
     * @param outTime the value for tp_baqry_user.out_time
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setOutTime(String outTime) {
        this.outTime = outTime == null ? null : outTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.in_time
     *
     * @return the value of tp_baqry_user.in_time
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public Date getInTime() {
        return inTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.in_time
     *
     * @param inTime the value for tp_baqry_user.in_time
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setInTime(Date inTime) {
        this.inTime = inTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.accomplices_way
     *
     * @return the value of tp_baqry_user.accomplices_way
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getAccomplicesWay() {
        return accomplicesWay;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.accomplices_way
     *
     * @param accomplicesWay the value for tp_baqry_user.accomplices_way
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setAccomplicesWay(String accomplicesWay) {
        this.accomplicesWay = accomplicesWay == null ? null : accomplicesWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.handling_area
     *
     * @return the value of tp_baqry_user.handling_area
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getHandlingArea() {
        return handlingArea;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.handling_area
     *
     * @param handlingArea the value for tp_baqry_user.handling_area
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setHandlingArea(String handlingArea) {
        this.handlingArea = handlingArea == null ? null : handlingArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.accomplices_reason
     *
     * @return the value of tp_baqry_user.accomplices_reason
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getAccomplicesReason() {
        return accomplicesReason;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.accomplices_reason
     *
     * @param accomplicesReason the value for tp_baqry_user.accomplices_reason
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setAccomplicesReason(String accomplicesReason) {
        this.accomplicesReason = accomplicesReason == null ? null : accomplicesReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.special_group
     *
     * @return the value of tp_baqry_user.special_group
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getSpecialGroup() {
        return specialGroup;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.special_group
     *
     * @param specialGroup the value for tp_baqry_user.special_group
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setSpecialGroup(String specialGroup) {
        this.specialGroup = specialGroup == null ? null : specialGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.person_type
     *
     * @return the value of tp_baqry_user.person_type
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getPersonType() {
        return personType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.person_type
     *
     * @param personType the value for tp_baqry_user.person_type
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setPersonType(String personType) {
        this.personType = personType == null ? null : personType.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.police_name
     *
     * @return the value of tp_baqry_user.police_name
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getPoliceName() {
        return policeName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.police_name
     *
     * @param policeName the value for tp_baqry_user.police_name
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setPoliceName(String policeName) {
        this.policeName = policeName == null ? null : policeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.handing_place
     *
     * @return the value of tp_baqry_user.handing_place
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getHandingPlace() {
        return handingPlace;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.handing_place
     *
     * @param handingPlace the value for tp_baqry_user.handing_place
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setHandingPlace(String handingPlace) {
        this.handingPlace = handingPlace == null ? null : handingPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.storage_tag
     *
     * @return the value of tp_baqry_user.storage_tag
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getStorageTag() {
        return storageTag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.storage_tag
     *
     * @param storageTag the value for tp_baqry_user.storage_tag
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setStorageTag(String storageTag) {
        this.storageTag = storageTag == null ? null : storageTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.bracelet_number
     *
     * @return the value of tp_baqry_user.bracelet_number
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getBraceletNumber() {
        return braceletNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.bracelet_number
     *
     * @param braceletNumber the value for tp_baqry_user.bracelet_number
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setBraceletNumber(String braceletNumber) {
        this.braceletNumber = braceletNumber == null ? null : braceletNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.storage_number
     *
     * @return the value of tp_baqry_user.storage_number
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getStorageNumber() {
        return storageNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.storage_number
     *
     * @param storageNumber the value for tp_baqry_user.storage_number
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setStorageNumber(String storageNumber) {
        this.storageNumber = storageNumber == null ? null : storageNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.is_warned
     *
     * @return the value of tp_baqry_user.is_warned
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getIsWarned() {
        return isWarned;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.is_warned
     *
     * @param isWarned the value for tp_baqry_user.is_warned
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setIsWarned(String isWarned) {
        this.isWarned = isWarned == null ? null : isWarned.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.alert_number
     *
     * @return the value of tp_baqry_user.alert_number
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getAlertNumber() {
        return alertNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.alert_number
     *
     * @param alertNumber the value for tp_baqry_user.alert_number
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setAlertNumber(String alertNumber) {
        this.alertNumber = alertNumber == null ? null : alertNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.word_number
     *
     * @return the value of tp_baqry_user.word_number
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getWordNumber() {
        return wordNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.word_number
     *
     * @param wordNumber the value for tp_baqry_user.word_number
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setWordNumber(String wordNumber) {
        this.wordNumber = wordNumber == null ? null : wordNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.medical_history
     *
     * @return the value of tp_baqry_user.medical_history
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getMedicalHistory() {
        return medicalHistory;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.medical_history
     *
     * @param medicalHistory the value for tp_baqry_user.medical_history
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setMedicalHistory(String medicalHistory) {
        this.medicalHistory = medicalHistory == null ? null : medicalHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.check_result
     *
     * @return the value of tp_baqry_user.check_result
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getCheckResult() {
        return checkResult;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.check_result
     *
     * @param checkResult the value for tp_baqry_user.check_result
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setCheckResult(String checkResult) {
        this.checkResult = checkResult == null ? null : checkResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.material_path
     *
     * @return the value of tp_baqry_user.material_path
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getMaterialPath() {
        return materialPath;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.material_path
     *
     * @param materialPath the value for tp_baqry_user.material_path
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setMaterialPath(String materialPath) {
        this.materialPath = materialPath == null ? null : materialPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.goods_photo
     *
     * @return the value of tp_baqry_user.goods_photo
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getGoodsPhoto() {
        return goodsPhoto;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.goods_photo
     *
     * @param goodsPhoto the value for tp_baqry_user.goods_photo
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setGoodsPhoto(String goodsPhoto) {
        this.goodsPhoto = goodsPhoto == null ? null : goodsPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.wait_room
     *
     * @return the value of tp_baqry_user.wait_room
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getWaitRoom() {
        return waitRoom;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.wait_room
     *
     * @param waitRoom the value for tp_baqry_user.wait_room
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setWaitRoom(String waitRoom) {
        this.waitRoom = waitRoom == null ? null : waitRoom.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.acquisition_project
     *
     * @return the value of tp_baqry_user.acquisition_project
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getAcquisitionProject() {
        return acquisitionProject;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.acquisition_project
     *
     * @param acquisitionProject the value for tp_baqry_user.acquisition_project
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setAcquisitionProject(String acquisitionProject) {
        this.acquisitionProject = acquisitionProject == null ? null : acquisitionProject.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.is_check
     *
     * @return the value of tp_baqry_user.is_check
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getIsCheck() {
        return isCheck;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.is_check
     *
     * @param isCheck the value for tp_baqry_user.is_check
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setIsCheck(String isCheck) {
        this.isCheck = isCheck == null ? null : isCheck.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.out_reason
     *
     * @return the value of tp_baqry_user.out_reason
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getOutReason() {
        return outReason;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.out_reason
     *
     * @param outReason the value for tp_baqry_user.out_reason
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setOutReason(String outReason) {
        this.outReason = outReason == null ? null : outReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.attachment
     *
     * @return the value of tp_baqry_user.attachment
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getAttachment() {
        return attachment;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.attachment
     *
     * @param attachment the value for tp_baqry_user.attachment
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setAttachment(String attachment) {
        this.attachment = attachment == null ? null : attachment.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.person_status
     *
     * @return the value of tp_baqry_user.person_status
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getPersonStatus() {
        return personStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.person_status
     *
     * @param personStatus the value for tp_baqry_user.person_status
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setPersonStatus(String personStatus) {
        this.personStatus = personStatus == null ? null : personStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.attachment_url
     *
     * @return the value of tp_baqry_user.attachment_url
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getAttachmentUrl() {
        return attachmentUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.attachment_url
     *
     * @param attachmentUrl the value for tp_baqry_user.attachment_url
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setAttachmentUrl(String attachmentUrl) {
        this.attachmentUrl = attachmentUrl == null ? null : attachmentUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.police_sign
     *
     * @return the value of tp_baqry_user.police_sign
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getPoliceSign() {
        return policeSign;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.police_sign
     *
     * @param policeSign the value for tp_baqry_user.police_sign
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setPoliceSign(String policeSign) {
        this.policeSign = policeSign == null ? null : policeSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.witness_sign
     *
     * @return the value of tp_baqry_user.witness_sign
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getWitnessSign() {
        return witnessSign;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.witness_sign
     *
     * @param witnessSign the value for tp_baqry_user.witness_sign
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setWitnessSign(String witnessSign) {
        this.witnessSign = witnessSign == null ? null : witnessSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.checked_sign
     *
     * @return the value of tp_baqry_user.checked_sign
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getCheckedSign() {
        return checkedSign;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.checked_sign
     *
     * @param checkedSign the value for tp_baqry_user.checked_sign
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setCheckedSign(String checkedSign) {
        this.checkedSign = checkedSign == null ? null : checkedSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.sponsor_sign
     *
     * @return the value of tp_baqry_user.sponsor_sign
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getSponsorSign() {
        return sponsorSign;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.sponsor_sign
     *
     * @param sponsorSign the value for tp_baqry_user.sponsor_sign
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setSponsorSign(String sponsorSign) {
        this.sponsorSign = sponsorSign == null ? null : sponsorSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.controll_sign
     *
     * @return the value of tp_baqry_user.controll_sign
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getControllSign() {
        return controllSign;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.controll_sign
     *
     * @param controllSign the value for tp_baqry_user.controll_sign
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setControllSign(String controllSign) {
        this.controllSign = controllSign == null ? null : controllSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.involved_sign
     *
     * @return the value of tp_baqry_user.involved_sign
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getInvolvedSign() {
        return involvedSign;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.involved_sign
     *
     * @param involvedSign the value for tp_baqry_user.involved_sign
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setInvolvedSign(String involvedSign) {
        this.involvedSign = involvedSign == null ? null : involvedSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.admin_sign
     *
     * @return the value of tp_baqry_user.admin_sign
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getAdminSign() {
        return adminSign;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.admin_sign
     *
     * @param adminSign the value for tp_baqry_user.admin_sign
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setAdminSign(String adminSign) {
        this.adminSign = adminSign == null ? null : adminSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.onpolice_sign
     *
     * @return the value of tp_baqry_user.onpolice_sign
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getOnpoliceSign() {
        return onpoliceSign;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.onpolice_sign
     *
     * @param onpoliceSign the value for tp_baqry_user.onpolice_sign
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setOnpoliceSign(String onpoliceSign) {
        this.onpoliceSign = onpoliceSign == null ? null : onpoliceSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.take_sign
     *
     * @return the value of tp_baqry_user.take_sign
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getTakeSign() {
        return takeSign;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.take_sign
     *
     * @param takeSign the value for tp_baqry_user.take_sign
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setTakeSign(String takeSign) {
        this.takeSign = takeSign == null ? null : takeSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.yqgy
     *
     * @return the value of tp_baqry_user.yqgy
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getYqgy() {
        return yqgy;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.yqgy
     *
     * @param yqgy the value for tp_baqry_user.yqgy
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setYqgy(String yqgy) {
        this.yqgy = yqgy == null ? null : yqgy.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.picture
     *
     * @return the value of tp_baqry_user.picture
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.picture
     *
     * @param picture the value for tp_baqry_user.picture
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.in_camera
     *
     * @return the value of tp_baqry_user.in_camera
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getInCamera() {
        return inCamera;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.in_camera
     *
     * @param inCamera the value for tp_baqry_user.in_camera
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setInCamera(String inCamera) {
        this.inCamera = inCamera == null ? null : inCamera.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.out_camera
     *
     * @return the value of tp_baqry_user.out_camera
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getOutCamera() {
        return outCamera;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.out_camera
     *
     * @param outCamera the value for tp_baqry_user.out_camera
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setOutCamera(String outCamera) {
        this.outCamera = outCamera == null ? null : outCamera.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.update_date
     *
     * @return the value of tp_baqry_user.update_date
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.update_date
     *
     * @param updateDate the value for tp_baqry_user.update_date
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate == null ? null : updateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.s
     *
     * @return the value of tp_baqry_user.s
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getS() {
        return s;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.s
     *
     * @param s the value for tp_baqry_user.s
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setS(String s) {
        this.s = s == null ? null : s.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.hd0
     *
     * @return the value of tp_baqry_user.hd0
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getHd0() {
        return hd0;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.hd0
     *
     * @param hd0 the value for tp_baqry_user.hd0
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setHd0(String hd0) {
        this.hd0 = hd0 == null ? null : hd0.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.bz0
     *
     * @return the value of tp_baqry_user.bz0
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getBz0() {
        return bz0;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.bz0
     *
     * @param bz0 the value for tp_baqry_user.bz0
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setBz0(String bz0) {
        this.bz0 = bz0 == null ? null : bz0.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.hd1
     *
     * @return the value of tp_baqry_user.hd1
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getHd1() {
        return hd1;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.hd1
     *
     * @param hd1 the value for tp_baqry_user.hd1
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setHd1(String hd1) {
        this.hd1 = hd1 == null ? null : hd1.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.bz1
     *
     * @return the value of tp_baqry_user.bz1
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getBz1() {
        return bz1;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.bz1
     *
     * @param bz1 the value for tp_baqry_user.bz1
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setBz1(String bz1) {
        this.bz1 = bz1 == null ? null : bz1.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.sign1
     *
     * @return the value of tp_baqry_user.sign1
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getSign1() {
        return sign1;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.sign1
     *
     * @param sign1 the value for tp_baqry_user.sign1
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setSign1(String sign1) {
        this.sign1 = sign1 == null ? null : sign1.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.sign2
     *
     * @return the value of tp_baqry_user.sign2
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getSign2() {
        return sign2;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.sign2
     *
     * @param sign2 the value for tp_baqry_user.sign2
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setSign2(String sign2) {
        this.sign2 = sign2 == null ? null : sign2.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.cd_check
     *
     * @return the value of tp_baqry_user.cd_check
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getCdCheck() {
        return cdCheck;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.cd_check
     *
     * @param cdCheck the value for tp_baqry_user.cd_check
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setCdCheck(String cdCheck) {
        this.cdCheck = cdCheck == null ? null : cdCheck.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.cd_code
     *
     * @return the value of tp_baqry_user.cd_code
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getCdCode() {
        return cdCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.cd_code
     *
     * @param cdCode the value for tp_baqry_user.cd_code
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setCdCode(String cdCode) {
        this.cdCode = cdCode == null ? null : cdCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.sftype
     *
     * @return the value of tp_baqry_user.sftype
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getSftype() {
        return sftype;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.sftype
     *
     * @param sftype the value for tp_baqry_user.sftype
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setSftype(String sftype) {
        this.sftype = sftype == null ? null : sftype.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.ajtype
     *
     * @return the value of tp_baqry_user.ajtype
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getAjtype() {
        return ajtype;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.ajtype
     *
     * @param ajtype the value for tp_baqry_user.ajtype
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setAjtype(String ajtype) {
        this.ajtype = ajtype == null ? null : ajtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tp_baqry_user.ystime
     *
     * @return the value of tp_baqry_user.ystime
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public String getYstime() {
        return ystime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tp_baqry_user.ystime
     *
     * @param ystime the value for tp_baqry_user.ystime
     * @mbggenerated Mon Jan 01 17:54:55 CST 2018
     */
    public void setYstime(String ystime) {
        this.ystime = ystime == null ? null : ystime.trim();
    }
}