package com.dsw.iot.dal.base;

import com.dsw.iot.model.PersonRelatedDo;
import com.dsw.iot.model.PersonRelatedDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersonRelatedDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_related
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    int countByExample(PersonRelatedDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_related
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    int deleteByPrimaryKey(PersonRelatedDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_related
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    int insert(PersonRelatedDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_related
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    int insertSelective(PersonRelatedDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_related
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    List<PersonRelatedDo> selectByExample(PersonRelatedDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_related
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    PersonRelatedDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_related
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") PersonRelatedDo record, @Param("example") PersonRelatedDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_related
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    int updateByExample(@Param("record") PersonRelatedDo record, @Param("example") PersonRelatedDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_related
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    int updateByPrimaryKeySelective(PersonRelatedDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_related
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    int updateByPrimaryKey(PersonRelatedDo record);
}