package com.dsw.iot.dal.base;

import com.dsw.iot.model.RemindDo;
import com.dsw.iot.model.RemindDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RemindDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remind
     *
     * @mbggenerated Sat Mar 03 15:12:19 CST 2018
     */
    int countByExample(RemindDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remind
     *
     * @mbggenerated Sat Mar 03 15:12:19 CST 2018
     */
    int deleteByPrimaryKey(RemindDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remind
     *
     * @mbggenerated Sat Mar 03 15:12:19 CST 2018
     */
    int insert(RemindDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remind
     *
     * @mbggenerated Sat Mar 03 15:12:19 CST 2018
     */
    int insertSelective(RemindDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remind
     *
     * @mbggenerated Sat Mar 03 15:12:19 CST 2018
     */
    List<RemindDo> selectByExample(RemindDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remind
     *
     * @mbggenerated Sat Mar 03 15:12:19 CST 2018
     */
    RemindDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remind
     *
     * @mbggenerated Sat Mar 03 15:12:19 CST 2018
     */
    int updateByExampleSelective(@Param("record") RemindDo record, @Param("example") RemindDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remind
     *
     * @mbggenerated Sat Mar 03 15:12:19 CST 2018
     */
    int updateByExample(@Param("record") RemindDo record, @Param("example") RemindDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remind
     *
     * @mbggenerated Sat Mar 03 15:12:19 CST 2018
     */
    int updateByPrimaryKeySelective(RemindDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remind
     *
     * @mbggenerated Sat Mar 03 15:12:19 CST 2018
     */
    int updateByPrimaryKey(RemindDo record);
}