package com.dsw.iot.dal.base;

import com.dsw.iot.model.UserRoleDo;
import com.dsw.iot.model.UserRoleDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRoleDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    int countByExample(UserRoleDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    int deleteByPrimaryKey(UserRoleDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    int insert(UserRoleDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    int insertSelective(UserRoleDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    List<UserRoleDo> selectByExample(UserRoleDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    UserRoleDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserRoleDo record, @Param("example") UserRoleDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    int updateByExample(@Param("record") UserRoleDo record, @Param("example") UserRoleDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    int updateByPrimaryKeySelective(UserRoleDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Thu Mar 01 11:47:52 CST 2018
     */
    int updateByPrimaryKey(UserRoleDo record);
}